### ISSUE TITLE
Cannot set up a backup – no error description given

### ISSUE THREAD

**Issue by max1mvs** [meganz/MEGAcmd#1007]
### MEGAcmd version

1.7.0

### Operating System/Platform

MacOS

### Platform version. In the case of Linux, please enter the Linux distribution you are using.

15.0 (24A335)

### Steps

Trying to set up a backup via this command:

`backup "/Volumes/Moose Backup" "/Backups/Mac Mini/Moose Backup" --period="0 0 4 * * *" --num-backups=1`

But I only get an error saying 'err:' with a timestamp like this:

`[err: 07:48:49]       backup (localpath remotepath --period="PERIODSTRING" --num-backups=N  | [-lhda] [TAG|localpath] [--period="PERIODSTRING"] [--num-backups=N]) [--time-format=FORMAT]`

It probably has something to do with the formatting, yet I have tried with single quotes, with no quotes, trailing slashes, and no trailing slashes in the file paths.

### Expected behavior

The backup to be set up, or at least an error stating what I am doing wrong.

### Actual behavior

I get an error without any explanation of the problem with my command.

**Comment by max1mvs** [comment]
It seems quiet around here…

**Comment by r1si** [comment]
If you downgrade , it works

Il mar 29 ott 2024, 09:25 Massimo Fiorentino ***@***.***> ha
scritto:

**Comment by max1mvs** [comment]
> If you downgrade , it works

Thanks! ⭐️
But downgrading is not something I am in favour of… 🤔

**Comment by polmr** [comment]
See https://github.com/meganz/MEGAcmd/issues/1009#issuecomment-2445438482

**Comment by dhanton** [comment]
This is indeed a _very old_ parsing issue; it will be fixed in the next release. Downgrading shouldn't help much :wink: Until then, as a workaround, make sure that the `--period` argument is the last one.

I.e., use
```
backup /some/path/tobackup/ /backups/ --num-backups=2 --period="0 0 4 * * *"
```
over
```
backup /some/path/tobackup/ /backups/ --period="0 0 4 * * *"  --num-backups=2
```
As explained in https://github.com/meganz/MEGAcmd/issues/1009#issuecomment-2445438482.
