### ISSUE TITLE
Cannot login in RHEL9 in Mega-CMD

### ISSUE THREAD

**Issue by Pooja1399pj** [meganz/MEGAcmd#1011]
### MEGAcmd version

1.2.0

### Operating System/Platform

Linux

### Platform version. In the case of Linux, please enter the Linux distribution you are using.

RHEL9

### Steps

I tried to install mega-cmd for RHEL9 but unfortunately i did not see any official packages for RHEL9 for mega-cmd so i installed mega-cmd RHEL8 which was available and after installation when i tired to login it says server is probably down try to respawn or reconnect it. But i tried to login in ubuntu it was logged in and did not throw any error. Please resolve this
<img width="948" alt="mega_cmd_in_redhat" src="https://github.com/user-attachments/assets/3bb4420f-2881-402b-ad07-749c1cf5557c">
![mega-cmd_in_ubuntu](https://github.com/user-attachments/assets/b7c11ea0-5a12-4d90-8144-4c40bb5ff0e8)

### Expected behavior

It should login in

### Actual behavior

after installation when i tired to login it says server is probably down try to respawn or reconnect it. But i tried to login in ubuntu it was logged in and did not throw any error.

**Comment by polmr** [comment]
Server is crashing. You may want to give a try to the newer version currently available for CentOS 8.
https://mega.nz/linux/repo/CentOS_8/x86_64/

However. none of these OS is currently supported for last MEGAcmd version. We suggest you to consider using alternatives to having MEGAcmd there (e.g: using MEGAcmd within a docker container), or consider compiling the project yourself.
