### ISSUE TITLE
Naming things is hard, but using badly named things is also hard.

### ISSUE THREAD

**Issue by prk0ghy** [meganz/MEGAcmd#1012]
### MEGAcmd version

1.7.0

### Operating System/Platform

Linux

### Platform version. In the case of Linux, please enter the Linux distribution you are using.

Fedora release 40 (Forty) MEGAcmd version: 1.7.0.21: code 1070021

### Steps

1. Try to stop a sync in `mega-cmd`.
2. type `sync --help`
3. "read" the options
```bash
Options:
-d | --remove ID|localpath      deletes a synchronization.
-s | --disable ID|localpath     stops(pauses) a synchronization.
-r | --enable ID|localpath      resumes a synchronization.
 --path-display-size=N  Use at least N characters for displaying paths.
 --show-handles Prints remote nodes handles (H:XXXXXXXX).
 --col-separator=X      Tt will use X as column separator. Otherwise the output will use
                         spaces to tabulate in an easy to read output:
 --output-cols=COLUMN_NAME_1,COLUMN_NAME2,...   You can select which columns to show (and their order) with this option
```
4. that is easy, I want to disable it so I type `sync -d ${ID}`

### Expected behavior

```bash
 -----------------------------------------------------------------------------------
|   Your sync /local/folder to: /mega/folder has transitioned to state Disabled     |
 -----------------------------------------------------------------------------------
```

### Denial.
This cant't be I dont make silly mistakes like this.
### Anger.
I am writing a bug report on about this!!!
### Bargaining.
Maybe I can also write my own pull request to fix my issue.
### Depression.
Wow none of this C++ Code makes any sense to me. At least now I know when I am alone there is a mega::MegaListener waiting for me.
### Acceptance.
`sync  /local/folder /mega/folder`
and next time `sync -s`

**Comment by prk0ghy** [comment]
No honestly please rename either the short or long options so both start with the same letter for same functionality.

**Comment by dhanton** [comment]
You're right that this is poorly named... same thing has happened to me several times :wink: We will take it into account and try to include these changes into next release. Thanks for the suggestion!
