### ISSUE TITLE
Improve share command

### ISSUE THREAD

**Issue by steve4444** [meganz/MEGAcmd#102]
The `invite` command has a convenient  `--message` option. Can you consider to add it to the `share` command too?
That would be helpful to clarify the scope of the share and, when there is no previous invitations, to  better identify the sender and reduce spam.

**Comment by polmr** [comment]
Similar discussion here: https://github.com/meganz/MEGAcmd/issues/12

**Comment by steve4444** [comment]
Sorry, forgot about that
