### ISSUE TITLE
Show  invitations older than n days

### ISSUE THREAD

**Issue by steve4444** [meganz/MEGAcmd#103]
In the GUI, under "Contacts" -> "Sent Requests", there is a convenient sortable "Sent" column. What about the API? 
I would like to filter `showpcr` output and show only invitations older than a given number of days.

**Comment by polmr** [comment]
Currently there's no immediate way to do that. Date is shown in a textual way, you can always grep the output of `mega-showpcr` looking for the certain days (e.g: `mega-showpcr | grep "2[5-9] Feb 2018"`), but nothing too fancy, we'll consider offering some sort of sorting mechanism.

**Comment by steve4444** [comment]
You could simply add an --iso [option](https://en.wikipedia.org/wiki/ISO_8601) showing dates like:

    2018-02-28T11:10:15+00:00


That would be realtively easy to parse and filter.

**Comment by polmr** [comment]
https://github.com/meganz/MEGAcmd/pull/114 <- this will give full flexibility regarding time outputs
