### ISSUE TITLE
Can not sync the hidden file to mega

### ISSUE THREAD

**Issue by koalang** [meganz/MEGAcmd#105]
some hidden files like .xxx.jpg can't be upload mega.

**Comment by polmr** [comment]
Files starting by `.` are excluded by default. You can remove the exclusion with `exclude -d ".*"`. Further info via `exclude --help`

**Comment by koalang** [comment]
> Files starting by `.` are excluded by default. You can remove the exclusion with
> 
> ```
> exclude -d ".*"
> ```
> Further info via `exclude --help`

Thanks a lot!
