### ISSUE TITLE
Delete Sync Debris (Trash) folder

### ISSUE THREAD

**Issue by Xoquito** [meganz/MEGAcmd#107]
I try to delete all files in trash folder with MEGAcmd (Windows version) but I can't. It's possible? or is a limitation of MEGAcmd?

Tx.

**Comment by Xoquito** [comment]
rm -r -f //bin/*

Sorry, I see older issue.

**Comment by TheHeurist** [comment]
What other folders/files are stored in // ?

**Comment by polmr** [comment]
none: `//bin` is one of the root folders or `mount points`. `/` is the cloud one, and there is `//in` for INBOX (see `cp --help`) and there could be other `mount points` for in-shares from other users. You can display them all using `mount`

**Comment by Cuchulain** [comment]
But You should execute this command from mega-cmd session, not from hosting system (linux/macos) :)

**Comment by sergiocabral** [comment]
> rm -r -f //bin/*

i just run this command into my cloud vm 🤯🫣😂
