### ISSUE TITLE
WebDAV android support

### ISSUE THREAD

**Issue by erotavlas85** [meganz/MEGAcmd#108]
Hi,
I'm using Android version 8.1 with official mega.nz app.
I just wonder to know if it is possible to use WebDAV with third party app.
Thank you

**Comment by polmr** [comment]
Wrong repo for this issue: https://github.com/meganz/android. In any case: Android official app does not support WebDAV serving.

**Comment by erotavlas85** [comment]
Ok, thank you. What is the right repository?

**Comment by polmr** [comment]
https://github.com/meganz/android
