### ISSUE TITLE
No password in script shell

### ISSUE THREAD

**Issue by REYNAUDNicolas** [meganz/MEGAcmd#115]
Hello !

I would to create a script without my password because i would write my password every time launch my script.

It's possible ? 

Thank you so much !
(OS : Ubuntu Server)

**Comment by polmr** [comment]
I'm not sure I understand your wording :-S
You don't need to insert your password everytime to use MEGAcmd. Once you log in, the session is stored in your computer and you will be logged in the next time you start MEGAcmd
