### ISSUE TITLE
Share/Invite enhancement

### ISSUE THREAD

**Issue by steve4444** [meganz/MEGAcmd#12]
Thanks for your great work, 0.9.6 works very well.
I found only a minor cosmetic issue in `userattr`. For the logged user the fields authring, lastinteraction, keyring are `NOT PRINTABLE`; for the other contacts the command gives the error `Failed to get user attribute ...: Access denied`. It would be better to remove these fields from the output, since in no case their value shows, or return a more sensible output in the second case (rather than an error).

I would also suggest a more relevant improvement. People managing file sharing with CLI scripts are expected to have huge number of contacts. When working in bulk, a project specific invite message is necessary for security reason (so that recipients trust the invitation). Currently this requires two distinct commands `invite` and  `share`. It would be better if the `share` command supported a message  argument like  `invite`, e.g.:

    share [-p] [-d|-a --with=user@email.com [--level=LEVEL]] [remotepath] [--message="MESSAGE"]

Consider that, with large numbers, one has also to setup a separate procedure to collect the email addresses, therefore a single share/invite command would make everything much smoother for the recipients.

**Comment by polmr** [comment]
Hi @steve4444 , sorry for the late reply.
`userattr` is somehow a low level utility. Those `NON PRINTABLE` attributes are shown there so as to know their existence. For other users, you don't have access to them, but they are still there nonetheless. The error seems logic IMHO. You can use `userattr NAMEOFTHEATTRIBUTE`, to gather the especific attribute you wish to read.
Concerning `share` and `invite`. sharing with a non-contact implicitly sends and invitation behind the curtains. If you want to send an invitation with a message, you can do it directly with `invite`, and then use `share`. It will not override the previous invitation. We didn't want to duplicate functionality and keep share simple.
