### ISSUE TITLE
megacli: Login failed: Expired

### ISSUE THREAD

**Issue by ncw** [meganz/MEGAcmd#121]
I can't seem to login with my account.  I get this on a megacli I just compiled from git master:

```
$ /opt/meganz-sdk/bin/megacli
MEGAcli> login me@myemail.com
Password:
Logging in...
Login failed: Expired
```

The account works fine in the web browser though.

If I try this with debug enabled I get

```
MEGAcli> login me@myemail.com
Password:
Logging in...
Resolving IPv4 address for g.api.mega.co.nz
c-ares info received
Received a valid IP for g.api.mega.co.nz: 31.216.147.135
Name resolution finished
cs POST target URL: https://g.api.mega.co.nz/cs?id=yiaevffcop&ak=Gk8DyQBS
cs Sending: [{"a":"us","user":"me@myemail.com","uh":"XXX","sek":"XXX","si":"XXX"}]
Using the IP of the hostname: 31.216.147.135
Setting cURL timeout to 0 ms
Disabling cURL timeout
Adding/setting curl socket 8
Setting cURL timeout to 0 ms
Disabling cURL timeout
Setting cURL timeout to 200 ms
Adding/setting curl socket 8
Adding/setting curl socket 8
Adding/setting curl socket 8
Removing socket 8
CURLMSG_DONE with HTTP status: 200 from g.api.mega.co.nz - 31.216.147.135
cs Received: [-8]
Setting cURL timeout to -1 ms
Login failed: Expired
```

Any ideas?

Thanks

**Comment by polmr** [comment]
Hi, 
For the moment MEGAcli lacks support for recently created accounts. 
You might want to try MEGAcmd (not MEGAcli): https://mega.nz/cmd if you want to use MEGA via console with that account

**Comment by ncw** [comment]
@polmr I get the same with mega-cmd (which I just compiled from the master branch) :-(

```
MEGA CMD> debug
CMD log level = VERBOSE
SDK log level = VERBOSE
MEGA CMD> login me@myemail.com
Password:
[err: 11:38:08] Failed to Login: Expired
```

**Comment by polmr** [comment]
that's unexpected ... Are you sure you have your project updated? what's the output of `version -l` within MEGAcmd?

**Comment by rawctl** [comment]
@polmr I'm having the same issue, but MEGAcmd works just fine. Any clue when this will be fixed in MEGAcli?

**Comment by ncw** [comment]
> Are you sure you have your project updated?

I checked it out from fresh from github using the instructions in the README for the test above

```
git clone https://github.com/meganz/MEGAcmd.git
git submodule update --init --recursive
```

Then I did

```
sh autogen.sh
./configure --prefix=/opt/megacmd
make
make install
```

> what's the output of `version -l` within MEGAcmd?

```
MEGA CMD> version -l
MEGA CMD version: 0.9.9: code 90900
MEGA SDK version: 3.3.5
MEGA SDK Credits: https://github.com/meganz/sdk/blob/master/CREDITS.md
MEGA SDK License: https://github.com/meganz/sdk/blob/master/LICENSE
MEGAcmd License: https://github.com/meganz/megacmd/blob/master/LICENSE
Features enabled:
* CryptoPP
* SQLite
* inotify
* fdopendir
* FreeImage
* PCRE
* sync subsystem
```

I don't know why it says SDK version 3.3.5 when the current version is 3.4.3, I guess that is the problem.

I don't have any versions of libmega (that locate can find) in a shared library directory so I can't figure out what is going on!

I tried a pre-compiled version of mega-cmd and it did work, so it looks like this is a build problem of some kind.  Perhaps the instructions need to be updated in some way? Or maybe there is something up with my machine!  I'm using ubuntu 18.04 BTW.

**Comment by polmr** [comment]
@rawctl Not sure, hopefully soon. Apologies for the inconvenience. We'd recommend using MEGAcmd though.

**Comment by ncw** [comment]
> Also, you need to ensure the server is restarted, maybe you have recompiled and are using the new version client, but the server (`mega-cmd-server`) was already running. `quit` within MEGAcmd console and restart should do.

That was the problem - thanks! (Duh!)

I made this issue because I was having the same problem that megacli has in https://github.com/t3rm1n4l/go-mega so I was looking for a clue to see what I needed to do, but I found to my suprise that megacli had the same problem.

Do you have a summary of the changes that happened to the protocol that caused the problem?  That is the new pre-registration call which provides a new salt which....

I know this is completely unsupported by MEGA but any help much appreciated - thanks :-)

**Comment by polmr** [comment]
`us0` is the command you are looking for. MEGAcli changes to support new accounts have been merged into `develop` here: https://github.com/meganz/sdk/pull/1278. If you are familiar with MEGAcli logic, it'll be straight forward to adapt them

**Comment by ncw** [comment]
@polmr thanks for your help.
