### ISSUE TITLE
Log in after restart, QNAP

### ISSUE THREAD

**Issue by salvq** [meganz/MEGAcmd#130]
Hello, I am having issue to use efficiently MEGAcmd 0.9.9.0 on QNAP.

I tried to login via interactive cmd shell and I am able to log in. Here is what I get when I exit interactive command shell and run whoami command, so far everything looks ok (IP, PASS and others are just made up or deleted).

```
[~] # /share/CACHEDEV1_DATA/.qpkg/MEGAcmd/mega-exec whoami -l
Account e-mail: xxxx@xxxx.com
    Available storage:200.00 GBytes
        In ROOT:      128.47 GBytes in 60458 file(s) and  2880 folder(s)
        In INBOX:       0.00  Bytes in     0 file(s) and     0 folder(s)
        In RUBBISH:    10.83 GBytes in  4193 file(s) and   877 folder(s)
        Total size taken up by file versions:      2.12 GBytes
    Pro level: 4
        Pro expiration date: Wed Jun 26 14:21:38 2019
    Subscription type:
    Account balance:
    Balance:     Balance: EUR 0.00

Current Active Sessions:
    * Current Session
    Session ID: XSW
    Session start: Wed Nov 28 14:39:53 2018
    Most recent activity: Wed Nov 28 14:39:54 2018
    IP: XX
    Country: XX
    User-Agent: MEGAcmd-QNAP/0.9.9.0 (qts 4.3.5/Linux 4.2.8 x86_64) MegaClient/3.3.5
    -----
    Session ID: XDR
    Session start: Tue Nov 27 13:08:22 2018
    Most recent activity: Tue Nov 27 13:08:23 2018
    IP: XX
    Country: XX
    User-Agent: MEGAiOS/4.3 (Darwin 18.2.0 iPhone9,3) MegaClient/3.4.4
    -----
    Session ID: TGH
    Session start: Tue Nov 27 12:43:15 2018
    Most recent activity: Tue Nov 27 12:43:16 2018
    IP: 195.26.25.240
    Country: XX
    User-Agent: MEGAcmd-QNAP/0.9.9.0 (qts 4.3.5/Linux 4.2.8 x86_64) MegaClient/3.3.5
    -----
3 active sessions opened
[~] #
```

The issue is when I restart QNAP, I am not logged anymore.

```
[~] # /share/CACHEDEV1_DATA/.qpkg/MEGAcmd/mega-exec whoami -l
[Initiating server in background. Log: /root/.megaCmd/megacmdserver.log]
Couln't initiate MEGAcmd server: executable not found: mega-cmd-server
Trying to use alternative executable: /share/CACHEDEV1_DATA/.qpkg/MEGAcmd/mega-c                                                               md-server
[err: 14:05:19] Not logged in.
```

Which is in collision what you describe on Local Cache part.

Local Cache
Logging in with MEGAcmd creates your Local Cache, a subfolder of your home folder. MEGAcmd downloads and stores some data in your Local Cache relating to your account, such as folder structure and contacts, for performance reasons. The MEGAcmd background server keeps the local cache up to date when changes to your account occur from other clients. The cache does contain a way for MEGAcmd to access your MEGA account when it starts up again if you have not specifically logged out. The Local Cache also contains information from your Session, including sync, backup, and webdav configurations. Logging out cleans the Local Cache, but also closes your session and the sync, backup, and webdav configurations are wiped.

1.) Is there any way I can log in and just being logged in even I restart the QNAP ? Am I doing something wrong ?
2.) Or possible to use some kind of ID (like session ID, session (secret)) within a script to execute login every restart ?

Thanks

**Comment by polmr** [comment]
Hi @salvq , 
1) the session should be saved in $HOME/megaCmd/session, you shouldn't need to login again. Notice that $HOME depends on your user: were you executing MEGAcmd with the same user when you logged in as the one you used after restarting (apparently `root`)? Is $HOME/.megaCmd available after restarting?
2) you can use the command `session`. That will print:
```Your (secret) session is: XXXXXXXX
```
 and then `login XXXXXXXX` afterwards, but that shouldn't be required

**Comment by mattw-mega** [comment]
It seems that QNAP deliberately removes those on restart.   However you can make a reliable place for MEGAcmd to store the local cache, by going to your QNAP settings app, in the Users tab, and turn on "Enable home folder for all users".     Once that is complete there will be a folder `/share/homes/root/` that can be used.   However you need to make sure to set `export HOME=/share/homes/root/` before running the first command (as that is when the `mega-cmd-server process` is started, and it uses that environment variable to know where to look for or create the `.megaCmd` folder).

**Comment by salvq** [comment]
I can confirm MEGAcmd is working by enabling HOME folder and setting HOME path (should be without the last slash: `export HOME=/share/homes/root`, some other QNAP has user `admin `instead of `root`) cmd is working fine.

Just a final question, is there any standard way how to add to megacmd to PATH, `export PATH=/share/CACHEDEV1_DATA/.qpkg/MEGAcmd:$PATH` in QNAP enviroment. I was not able to find way other that manual via shell after every restart.

Thanks

**Comment by polmr** [comment]
thanks for pointing the unrequired trailing slash. Regarding your question, you can add that very line to the end of `~/.bashrc` (I'm assuming you are using `bash` shell). Thus, it'll be available every time you login into a shell.

**Comment by salvq** [comment]
Thanks for all the help.

QNAP is bit different, .bashrc is being overwritten every restart i.e. it is copied from RAM disk so changing bash...will not help.

Anyway, here is fix for anybody looking how to fix $PATH extend issue...
