### ISSUE TITLE
mega-login: 2FA code as command line argument

### ISSUE THREAD

**Issue by joshirio** [meganz/MEGAcmd#132]
The interactive cmd shell and the mega-login executable ask for the 2FA code if the account uses 2FA. It would be helpful to allow to specify the 2FA code as an optional argument, since mega-login already uses the account email and password as command line parameters.

mega-login email password [6 digit 2FA code]

Please consider implementing this feature to allow scripts to login without requiring an interactive shell.

**Comment by Mr1262** [comment]
Hello 
Please could you help me to get 6-digit code mega ?

**Comment by hialvaro** [comment]
Has this been added?

**Comment by Rogier-E** [comment]
I just stumbled upon this old topic while dealing with the same issue. 
For what it's worth, notice that you can supply the 2FA code from stdin by piping it to `mega-login`, like so:

`echo '123456' | mega-login email password`

**Comment by polmr** [comment]
Also via:
```
mega-login email password --auth-code=123456
```

**Comment by evele** [comment]
mmm .. but how I get the code automatically?
