### ISSUE TITLE
where is ffmpeg-mega ?

### ISSUE THREAD

**Issue by komusubi** [meganz/MEGAcmd#135]
Hi, 
I use megacmd on rasberry pi 3(fedora 29 server) with build by myself.

I got src rpm from https://mega.nz/linux/MEGAsync/Fedora_29/src/megacmd-1.0.0-1.src.rpm 
and builddep (dnf builddep megacmd.spec) but not found ffmpeg-mega.

I looked for it but could NOT found ffmped-mega.
Please teach me where is ffmpeg-mega rpm package, if you can.

**Comment by polmr** [comment]
Hi @komusubi , it's nowhere, is just a prebuilt dependency we use to for building with ffmpeg libs. You can remove it from the .spec file and install ffmpeg-devel instead. Let us know if you find any issue. Alternatively you might want to follow instructions at https://github.com/meganz/MEGAsync

**Comment by komusubi** [comment]
Hi @polmr thank you reply.
I tried rpmbuild  but failed again.
It is reason arm architecture build option.

error log from sdk_build/build/freeimage-3170/FreeImag
>  relocation R_ARM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC

anyway, it seems to need install ffpmeg-devel. 
I close this issue.
