### ISSUE TITLE
Export link additions

### ISSUE THREAD

**Issue by someguy1616** [meganz/MEGAcmd#138]
Hi,

Would it be possible to add support for obtaining a share link with a password, or with or without the decryption key attached?

Thanks.

**Comment by polmr** [comment]
If you have a PRO account, you can do
```
export -a --password=YOURPASSWORD /path/to/file
```
to export a password protected link. We will consider adding some --do-not-show-decryption-key flag.

**Comment by someguy1616** [comment]
Worked great, thank you. Please consider the suggestion of adding it the UserGuide.md
