### ISSUE TITLE
Impossible to download child folders

### ISSUE THREAD

**Issue by OblackatO** [meganz/MEGAcmd#139]
I have a MEGA link that points to one folder, inside this folder X, there are several other folders. They are each identified by a !"some characters" at the end of the link of the parent folder X. 

When I try to download any of them, with their respective link, using: mega-get "link to sub folder of X" , the X folder is download instead, meaning all the sub folders of X are downloaded. 

This behavior happens for any folder inside X.  Is this a bug?

**Comment by OblackatO** [comment]
A solution would be to import the sub folder of X that needs to be downloaded and get the link once it is imported.

**Comment by polmr** [comment]
Directly addressing files/folder within a folder link it's not supported yet. It will be in the future. Currently you can opt for your solution (import+get) or you can login into a public folder. (see mega-login --help). But you'll need to logout from your account first.
