### ISSUE TITLE
I have no idea what iam doing, but it's stuck with "RETRYING"

### ISSUE THREAD

**Issue by AMDJona** [meganz/MEGAcmd#142]
Hey, just installed the newest version of MEGAcmd on my Ubuntu 18.04 Server.
After logging in, I did "mega-get link" to download my file, which worked very well.  After an hour I came back to check in. The File is 6.46GB and it's stuck at 69.36%. The STATE is "RETRYING" , restart didn't help.
On my Windows Computer I can download the same file just fine (uses the same account and ip) 
My 240GB SSD on my Server has over +200gb free, that should't be a problem. 
Maybe you could help me solve this issue, 
Can't find any log files I'm sorry

**Comment by AMDJona** [comment]
fixed itself after restarting the router... Still no Idea why, because my PC could download so it wasn't an IP block problem....

**Comment by polmr** [comment]
Seems like it was some temporary connectivity issue. In case it happens again, there should be a log in ~/.megaCmd/megacmdserver.log. That might give us some extra info. You can also increase log verbosity by executing `mega-log DEBUG` in a separate console.
