### ISSUE TITLE
Interact with MEGAcmdServer

### ISSUE THREAD

**Issue by EliuX** [meganz/MEGAcmd#144]
## Problem
Whenever you run a MEGAcmd command for the first time the server will start automatically:
>Initiating server in background. Log: /home/travis/.megaCmd/megacmdserver.log

But when you try to check which commands the `MEGAcmdServer` server provides you get as response

> Another instance of MEGAcmd Server is running. Execute with --skip-lock-check to force running (NOT RECOMMENDED)

## Wanted solution
It would be nice to have commands to manipulate the `MEGAcmdServer`, e.g.
* `start`: Starts the server right away
* `stop`: Stops a running server
* `status`: Gives information about the running server (PID, used ports, etc.)
* `help`:  Provide help about the available commands

## Scope
Right now I am trying to [fix a contrib library issue](https://github.com/EliuX/MEGAcmd4J/issues/8) but its not really possible to interact with the  `MEGAcmdServer`.

**Comment by polmr** [comment]
Hi @EliuX, I'm not sure how did you got to this

>But when you try to check which commands the MEGAcmdServer server provides you get as response...

What did you do exactly?

Regarding your wanted solution: what you asked can already be done already somehow:
>start: Starts the server right away

To launch the server manually in linux you can simply execute `mega-cmd-server` in a shell
>stop: Stops a running server

This can be done in different ways
```
CTRL+C in the console that launched the server
mega-quit
killall -2 `pgrep mega-cmd-server`
```
>status: Gives information about the running server (PID, used ports, etc.)

```
pgrep mega-cmd-server
lsof -p `pgrep mega-cmd-server`
```
> help: Provide help about the available commands

```
mega-help
```

Let us know if you need further assistance

**Comment by EliuX** [comment]
Hi @polmr, thanks for your quick response. 

>What did you do exactly?

I am working in a Windows workstation (using GNU bash, version 4.4.12(1)-release-(x86_64-pc-msys)) where there is a `MEGAcmdServer` binary in `c/Users/eliec/AppData/Local/MEGAcmd/MEGAcmdServer`:
* If before executing any MEGAcmd command you execute `MEGAcmdServer --help`, you get a console banner that says in ascii art
    > MEGAcmd 
        server

* Afterwards I executed my first MEGAcmd command in the day, e.g. `version`, and the server started:
```
D:\development\workspace\Mega\megacmd4j>MegaClient version
Server not running. Initiating in the background...
MEGA CMD version: 1.0.0: code 1000000
```
> To launch the server manually in linux you can simply execute mega-cmd-server in a shell

I imagine in that in Windows it would be `MEGAcmdServer`. The first time I executed it, asking for `help`, it showed me a banner, it got some time in the console without printing or taking any input, then I tried my first command and that was the moment when the server started. Afterwards I tried the server command again and I got this answer:
```
$ MEGAcmdServer
Another instance of MEGAcmd Server is running. Execute with --skip-lock-check to force running (NOT RECOMMENDED)
```
>This can be done in different ways

Yes, those ways are Ok for a devOps task in Unix based OS, but I would need a solution for the [issue ](https://github.com/EliuX/MEGAcmd4J/issues/8) I am tackling in [MEGAcmd4J](https://github.com/EliuX/MEGAcmd4J) that can be used for different OS.

Thank you very much for your feedback.

**Comment by polmr** [comment]
> Hi @polmr, thanks for your quick response.
> 
> > What did you do exactly?
> 
> I am working in a Windows workstation (using GNU bash, version 4.4.12(1)-release-(x86_64-pc-msys)) where there is a `MEGAcmdServer` binary in `c/Users/eliec/AppData/Local/MEGAcmd/MEGAcmdServer`:
> 
> * Before executing any MEGAcmd command, I executed `MEGAcmdServer --help`, and got a console banner that says in ascii art
>   > MEGAcmd
>   > server

^ So, let's see what's happening. `MEGAcmdServer.exe` initiates the server *IN FOREGROUND*. And it lays there silently waiting for clients to connect. Passing `--help` as parameter does nothing to the server. If you want it (you don't ;-) ) to be more verbose and print more stuff execute it with `MEGAcmdServer --debug-full`. 

> * Afterwards I executed my first MEGAcmd command of the day, i.e. `version`, and the server started:
> 
> ```
> D:\development\workspace\Mega\megacmd4j>MegaClient version
> Server not running. Initiating in the background...
> MEGA CMD version: 1.0.0: code 1000000
> ```

I understand you first closed the server. When you execute `MegaClient version` it will try to communicate with the server. If no server is listening, it starts one IN BACKGROUND. If you had kept the server running it wouldn't have started it in the background.

> > To launch the server manually in linux you can simply execute mega-cmd-server in a shell
> 
> I imagine in that in Windows it would be `MEGAcmdServer`. The first time I executed it, it showed me a banner, it got some time in the console without printing any output or taking any input. Then I tried my first command and that was the moment when the server started. Afterwards I tried the server command again and I got this answer:
> 
> ```
> $ MEGAcmdServer
> Another instance of MEGAcmd Server is running. Execute with --skip-lock-check to force running (NOT RECOMMENDED)
> ```

This second time, there is a MEGAcmdServer running in the background (you will see it in your Task Manager). Hence, it won't let you start another.

> > This can be done in different ways
> 
> Yes, those ways are Ok for a devOps task in Unix based OS, but I would need a solution for the [issue ](https://github.com/EliuX/MEGAcmd4J/issues/8) I am tackling in [MEGAcmd4J](https://github.com/EliuX/MEGAcmd4J) that can be used in different operative systems.
> 

Sorry, given your paths I assumed you were on linux. Let's see how could we do what you wanted:

> start: Starts the server right away

you can execute some OS dependent stuff. for instance, in cmd.exe you can execute something  like `START /B MEGAcmdServer`, but that will mix the server output with whatever you execute next, or you can execute some client command. e.g: `mega-version` and that will launch the server for you (assuming you have .bat scripts in your PATH)

> stop: Stops a running server

`mega-quit` (= MEGAClient.exe quit) will do

>status: Gives information about the running server (PID, used ports, etc.)

There is no OS agnostic way to do that provided by MEGAcmd. 

>help: Provide help about the available commands

`mega-help`  (= MEGAClient help) will do

**Comment by EliuX** [comment]
Hi @polmr,
Thanks, with what you mentioned it will be enough for me to start and stop the `MEGAcmdServer`. 

Nonetheless I still think that a `start` command could be a nice complement to `quit`. Although I could also simulate the `start` using `version`; specially if you think the command feels like bloatware.

**Comment by polmr** [comment]
Great to hear that. We will think about the `mega-start` although it could be missleading: any command should initiate the server: not so sure if we need one that does nothing ;-)
