### ISSUE TITLE
WEBDAV.md documentation

### ISSUE THREAD

**Issue by jpeacock29** [meganz/MEGAcmd#145]
It would be helpful if all the docs, including WEBDAV.md, mention that the commands provided are to be run within the mega-cmd shell. Furthermore, the example webdav server should indicate that a path relatively to the MEGA cloud should be passed, not the local machine.

**Comment by polmr** [comment]
WEBDAV.md already refers to remote files:

"Configuring a WEBDAV server will let you access **your MEGA files** as if they were located in your computer"

Anyway, we will try to clarify all that in the docs a little more. Thanks for your inputs!

**Comment by jpeacock29** [comment]
Thank you for your response! I was referring specifically to the first example:

    webdav /path/to/myfolder

might be more clear as 

    webdav /path/to/folder/on/mega
