### ISSUE TITLE
`webdav` ignores passed arguments

### ISSUE THREAD

**Issue by ritiek** [meganz/MEGAcmd#148]
Hi, this tool is very useful to me. Thanks a lot for making this!

I'm trying to change the port and set the webdav to listen on 0.0.0.0 but for some reason the arguments I pass to the command get ignored.

For example:

(I ran this command in `mega-cmd` shell:)
```
$ webdav MEGAsync/test.txt --port=6060 --public                       
Serving via webdav /MEGAsync/test.txt: http://127.0.0.1:4443/xxxxxxxx/test.txt 
```
It outputs to be listening on port 4443 and when I check it from my web-browser, it indeed runs on port 4443 and is still localhost only. In the perfect world, it should listen to port 6060 and be publicly accessible.

I installed MEGAcmd from https://mega.nz/cmd if it helps.
```bash
$ mega-version
MEGA CMD version: 1.0.0: code 1000000
```

Let me know if there is any additional information I could provide.

**Comment by ritiek** [comment]
I was able to set these options by first killing the `mega-cmd-server` process (`$ pkill -f mega-cmd-server`), then modifying `~/.megaCmd/megacmd.cfg` and finally running the `webdav` command again. However, directly passing these options as arguments still doesn't seem to work for me.

**Comment by polmr** [comment]
This issue is a consequence of what's said in the inline doc of webdav command (see `webdav --help`): 
```
*If you serve more than one location, these parameters will be ignored and use those of the first location served.
```
Removing all served locations and reconfiguring it again should have also worked:
```
webdav -d --all
```
We will try to improve the docs to explain that a little better, thanks for spotting it

**Comment by ritiek** [comment]
Thanks!
```
webdav -d --all
```
solved for me.

Yep, I think it would be a good idea to clarify this in webdav docs!
