### ISSUE TITLE
Megatools to MEGAcmd

### ISSUE THREAD

**Issue by extensionsapp** [meganz/MEGAcmd#155]
Hello,

This unofficial client not work https://github.com/megous/megatools

Please tell me the alternative commands in MEGAcmd:
`rm       Remove remote file or directory` use `megatools rm -u "email" -p "pass" /Root/dir`
`mkdir  Create remote directory` use `megatools mkdir -u "email" -p "pass" /Root/dir`
`put      Upload individual files` use `megatools put -u "email" -p "pass" --path /Root/dir /var/put.tar`
`get      Download individual files` use `megatools get -u "email" -p "pass" --path /var /Root/dir/put.tar`

Thanks for the answer.

**Comment by polmr** [comment]
We would recommend you to read the documentation at https://github.com/meganz/MEGAcmd to understand how MEGAcmd works. In any case, this should do:
First you'd need to login:
```
mega-login email pass
```
then
```
mega-rm -r /Root/dir
mega-mkdir /Root/dir
mega-put -r /var/put.tar /root/dir/
mega-get -r /Root/dir/put.tar /var/
```

**Comment by extensionsapp** [comment]
Hello.
You have a very good command line client.
Add more usage examples to the documentation.
```
mega-rm -r -f /dir
mega-put -c /var/put.tar /dir/
mega-get -r /dir/put.tar /var/
...
```
I thought for 2 years that these commands are not in the client, since they are not described in the documentation.

**Comment by polmr** [comment]
There's a list of all available commands in the user guide [here:](https://github.com/meganz/MEGAcmd/blob/master/UserGuide.md#command-summary) . We will try to make that more visible!

**Comment by polmr** [comment]
Forever, until closed via `logout` or remotely. See [this:](https://github.com/meganz/megacmd#usage)
