### ISSUE TITLE
webdav : Location not available / Incorrect Parameter

### ISSUE THREAD

**Issue by Craftonix** [meganz/MEGAcmd#162]
When i try to use the webdav function to mount a drive in windows 10
i access first level of root dir, but when accessing a folder with many subfolder and file, i got an error :
Location is not available
Z:\_myfolder_\ is not available
parameter is incorrect

When i access from firefox (http://127.0.0.1:4443/..../Cloud Drive/) it works

I think is it related to character in filename accepted or not in windows  but not sure, i would like to find a log to show what make the error but can find anything.

PS : I'm using latest version of windows 10 (1809, tested with 1803) and latest megacmd

**Comment by polmr** [comment]
Hi @Craftonix , there are issues with certain characters. There's a fix in the `sdk` for that that will be included in the next release of MEGAcmd to avoid problems with certain characters: https://github.com/meganz/sdk/pull/1250/files#diff-4d3039dff574b788948119de402ca8d9R1259

**Comment by polmr** [comment]
There's a new version of MEGAcmd 1.1.0 for Windows available at https://mega.nz/cmd that has the fix above included

**Comment by dreamlabnetwork** [comment]
I am having this issue. Using the most up to date version. It is happening on several devices. It works then stops working. Then works. then stops working again.
