### ISSUE TITLE
Delete last command history on login

### ISSUE THREAD

**Issue by cjrocks** [meganz/MEGAcmd#168]
When you login with PowerShell or linux console, by plain text password, history is keept in command history log (when you use scripting")

I think that MEGAcmd should handle bash/PowerShell history to remove last entry, and prevent future de-anonymization of the password, like other UNIX/Windows commands do.

**Comment by polmr** [comment]
Hi @cjrocks ,
MEGAcmd Client does not know who invoked it. It just receives parameters as arguments. Plus, tempering with shell history could lead to other complications and not everybody will want the exact command used to be removed from the history. 

If you don't want to have the password in your shell history, you can invoke it using some environment variable.

**Comment by cjrocks** [comment]
> 
> 
> Hi @cjrocks ,
> MEGAcmd Client does not know who invoked it. It just receives parameters as arguments. Plus, tempering with shell history could lead to other complications and not everybody will want the exact command used to be removed from the history.
> 
> If you don't want to have the password in your shell history, you can invoke it using some environment variable.

Great idea! I haven't realized that environment variables can be used.

**Comment by cjrocks** [comment]
Closing issue
