### ISSUE TITLE
MEGAcmd sync

### ISSUE THREAD

**Issue by steve4444** [meganz/MEGAcmd#18]
In Windows, when using `sync` I don't see the synced folders set with MEGAsync. Is this the intended behaviour (two different sync channel)?

**Comment by polmr** [comment]
MEGAcmd & MEGAsync work completely separated. They are both sync clients. You can either sync a local-remote folder with any of the two. They don't communicate with each other. Do not sync the same folder with both of them. The behavior might be unexpected.

**Comment by steve4444** [comment]
>  Do not sync the same folder with both of them. The behavior might be unexpected.

That's good to know!
