### ISSUE TITLE
update command line pops up every half hour

### ISSUE THREAD

**Issue by markifi** [meganz/MEGAcmd#188]
even when I'm not using megaclient, it seems to be scheduled but I can't find it
even when I turn updates off

**Comment by polmr** [comment]
Ey @markifi , Where does it pop up? what's your OS. Would you be kind enough to post whatever you are receiving? IIRC updates within MEGAcmd 1.1.0 are consulted every 2 hours. and `update --auto=off` should disable them. `update --auto=query` should report `Automatic updates disabled` if that's the case

**Comment by markifi** [comment]
oh, sorry, yeah, that was silly of me.
it looks like this:
https://i.imgur.com/T5cby89.png
it's windows 8.1 pro 64 bit
update --auto=off doesn't help it

**Comment by markifi** [comment]
megaclient update --auto=off
megaclient update --auto=query
right?
because even in Administrator mode, it doesn't help

**Comment by markifi** [comment]
Any other ways of disabling this? query says disabled, but it still happens

**Comment by markifi** [comment]
I deleted the updater from %localappdata%/MEGAcmd (one of the five .exe files, located under C:\Users\userfolder\AppData\Local\MEGAcmd, has update in the name), and that helped.
