### ISSUE TITLE
Updating MEGAcmd messes up sync job

### ISSUE THREAD

**Issue by 0yz** [meganz/MEGAcmd#193]
I'm running on Debian 9 (latest updates) and i have set up one folder to be synced by MEGAcmd.
This worked fine until 2 days ago when i ran "apt-get update". 
MEGAcmd stopped syncing the folder and i have files that never got synced.

The folder that i'm syncing contains *.tar.gz archives that get automatically created every 20 minutes by a script that also removes any files older than 72 hours. The backups have the current date and time as name. 

After i've found out that it's not syncing the files anymore i restarted MEGAcmd and it started syncing again but it only uploaded new files and it left a hole of missing files.
So after the file "20190423_1340.tar.gz" comes the file "20190425_0940.tar.gz" and all files between these 2 are missing and are not being synced even though they exist on the local Linux hard drive. It also doesn't remove the files that have been deleted by the script locally and that messed up my automatic backup job.

How can I avoid MEGAcmd not working after updating and can i somehow force a sync so the MEGA directory contains the same files as my local directory?

Would it work if i: Remove the sync job > Delete the files from MEGA myself > Create the sync job again?
Would that upload all files from my local folder to MEGA and make it sync properly again?

**Comment by polmr** [comment]
It seems that local cache has been broken somehow. `mega-reload` might help.

**Comment by 0yz** [comment]
Thank you! i solved this by adding mega-reload at the beginning of my backup script so i don't need to execute it after an update or system reboot.
