### ISSUE TITLE
Installation of megacmd on Ubuntu 16.04

### ISSUE THREAD

**Issue by PeterEricssonEnhet** [meganz/MEGAcmd#21]
Hi,
I tried to follow your guide to install megacmd on my Ubuntu Server 16.04.

First I cloned the the git repository.

I installed all packaged as suggested on GIT for 16.04
`autoconf libtool g++ libcrypto++-dev libz-dev sqlite3-dev libsqlite3-dev libssl-dev libcurl4-openssl-dev libreadline-dev libpcre++-dev libsodium-dev`

This one could not be found: **sqlite3-dev**.

1. sh autogen.sh - > looked like it worked
2. ./configure 
`checking ZenLib/Ztring.h usability... no
checking ZenLib/Ztring.h presence... no
checking for ZenLib/Ztring.h... no
checking for pthread_create in -lpthread... (cached) yes
libmediainfo requires libzen
checking for aio_write in -lrt... yes
checking for OpenSSL... --with-openssl not specified
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for SSL_new in -lssl... yes
checking for c-ares... --with-cares not specified
checking ares.h usability... no
checking ares.h presence... no
checking for ares.h... no
configure: error: ares.h header not found or not usable
configure: error: ./configure failed for sdk
`
I really would like to use MEGAsync on my server, but I have to stay with Dropbox unless you have a solution to these install issues.

Thanks
Peter

**Comment by CTrauma** [comment]
Try installing **libsqlite3-dev** instead of **sqlite3-dev**

**Comment by polmr** [comment]
@PeterEricssonEnhet You'd need `libc-ares-dev` to fix that error.

**Comment by altagir** [comment]
`sudo apt-get install libfreeimage-dev`
as well
