### ISSUE TITLE
Cannot access ftp without a file or folder in ftp root when creating it / windows explorer

### ISSUE THREAD

**Issue by cutter6** [meganz/MEGAcmd#210]
I have windows 10 pc and when I created an ftp folder with megacmd I could not access it. I did not have anything in the folder. I created another ftp with a mega.nz folder that had data in it, and it worked perfect when accessing it thru file explorer. Make sure your ftp folder has something in it!! Not a big issue but I wanted to contribute, I love MEGA.NZ!!

![megacmd ftp](https://user-images.githubusercontent.com/51417916/58978809-a71e3980-879a-11e9-8077-7c358bf9beb4.JPG)

**Comment by polmr** [comment]
nice catch @cutter6 , thanks for reporting that
