### ISSUE TITLE
autogen.sh: 2: autogen.sh: autoreconf: not found

### ISSUE THREAD

**Issue by world4jason** [meganz/MEGAcmd#218]
autogen.sh: 2: autogen.sh: autoreconf: not found

**Comment by polmr** [comment]
You need to install autoreconf. In Ubuntu: `sudo apt install autoconf`

**Comment by B1991ing** [comment]
Dear developer,

One error happened that "songbing@songbingdeMacBook-Pro vsearch % sudo apt install autoconf
Password:
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java."

how to solve it according to your experience?

Best,

Bing
