### ISSUE TITLE
[docs] Improve build instructions

### ISSUE THREAD

**Issue by drakulis** [meganz/MEGAcmd#219]
I've successfully build MEGAcmd for my (unsupported) armv5tel processor (NSA-310 nas server). Everything works great and I would like to create deb package to avoid long compilation in the future. Unfortunately I have no idea how to do it (i'm not linux expert) and I can't find any instructions in documentation.

Would be great if documentation could contains such instructions.

**Comment by polmr** [comment]
Hi, we will consider adding some notes regarding that. In the meantime, this might help  you:
```
#as root
rm -r /tmp/buildfolder/requiredfiles
mkdir -p /tmp/buildfolder/requiredfiles
cd /tmp/buildfolder
rm -r megacmd
git clone --recursive --branch 1.1.0_Linux https://github.com/meganz/megacmd
cd megacmd
cd build
./create_tarball.sh
cp ./megacmd/* /tmp/buildfolder/requiredfiles/
cd /tmp/buildfolder/requiredfiles
mkdir debian
for i in debian.*; do ln -sf ../$i debian/"${i/debian./}"; done
tar xvzf megacmd_*tar.gz
mv megacmd-*/* ./
debuild -b -uc -us
```

You will need to have all dependencies plus `devscripts` at least

**Comment by drakulis** [comment]
It works! Thank you!
