### ISSUE TITLE
Sync returns output to write in socket 43: <<>>

### ISSUE THREAD

**Issue by ronilaukkarinen** [meganz/MEGAcmd#227]
Hello. I'm trying to sync files on Fedora 25. It returns `[verbose: 13:08:19] Output to write in socket 43: <<>>` whatever I try to do. I have logged in. Any help?

**Comment by polmr** [comment]
It seems you have set the log into verbose mode. You can decrease log verbosity this way:open a new console, execute `mega-cmd` and then ```log INFO```,

**Comment by ronilaukkarinen** [comment]
But the sync should still do something, right? I doesn't sync any files and that's my main issue here. I do not get any other output. Sorry for not being clear about that.

**Comment by polmr** [comment]
If you have configured your sync correctly, you can execute
```
mega-sync
```
with no arguments and will see your configured sync. Further info `sync --help` , https://github.com/meganz/MEGAcmd/blob/master/README.md & https://github.com/meganz/MEGAcmd/blob/master/UserGuide.md

**Comment by ronilaukkarinen** [comment]
Ah I see. It needs other than root dir, made it with mega-mkdir and now it all syncs fine. Verbose things look like error so that was a bit confusing. Thanks!
