### ISSUE TITLE
Backup command returns [err: 12:57:39] / not found

### ISSUE THREAD

**Issue by ronilaukkarinen** [meganz/MEGAcmd#228]
Hello. I'm trying to backup files to Mega directory root Fedora 25.

Command `mega-backup /backups / --period=“0 0 4 * * *” --num-backups=30` returns `[err: 12:57:39] / not found`. /backups dir exists.

With root the output is as following with full verbosity:

```
ERROR writing MCMD_PARTIALOUT to socket: 32
WARNING: Client disconnected, the rest of the output will be discarded
[err: 13:13:38] / must be a valid folder
[verbose: 13:13:38]  Procesed backup --path-display-size=45 -vvv /backups / "--period=0 0 4 * * *" --num-backups=30 in thread: 139995522094848 socket output: 72
[verbose: 13:13:38] Output to write in socket 72: <<>>
```

What to do? documentation didn't help.

**Comment by polmr** [comment]
try to set the backup into a non-root folder (currently that's not enabled I'm afraid):

**Comment by ronilaukkarinen** [comment]
Ah I see. It needs other than root dir, made it with `mega-mkdir` and now it all syncs fine. Verbose things look like error so that was a bit confusing. Thanks!

**Comment by ronilaukkarinen** [comment]
Got it, thanks!
