### ISSUE TITLE
mega-help not working while using the fish shell

### ISSUE THREAD

**Issue by fnicolini** [meganz/MEGAcmd#23]
I have fish as my user default shell and when running the command ```mega-help``` this is what i get:

```The file '/usr/bin/mega-help' is marked as an executable but could not be run by the operating system.```

Is there a way to make it work on fish as well? (when i run it on bash it works properly)

**Comment by polmr** [comment]
You can preppend this line
```
#!/bin/bash
```
at the beginning of the file /usr/bin/mega-help or use 
```
bash mega-help
```
Maybe we should enforce bash as the default interpreter on every command installed at `/usr/bin/mega-*`

**Comment by polmr** [comment]
Done in the new release `1.0.0`
