### ISSUE TITLE
File Upload Permissions

### ISSUE THREAD

**Issue by dersch** [meganz/MEGAcmd#230]
Good afternoon, 

I'm seeing a huge issue when uploading files via mega-sync. The files display correctly within the site and the mobile application, but on my CentOS server, they get created with 600 permissions. 

*.) I've tried adjusting default (f)ACLs on the direcories;
*.) I've tried messing with umask values for the user/group/other;
*.) Since this isn't running as a service/daemon, I don't believe I can adjust what umask the mega process is running as;
*.) I didn't notice a setting anywhere within the account for file permissions; 

Is there something I'm missing? I'm running out of ideas on how to get these files to go to Linux with the correct permissions (at least need 644), whether it be something in Mega or in Linux that I'm not thinking of. 

Thank you a lot for the help.

**Comment by dersch** [comment]
Quick thought:

ACLs only apply to new files/directories being created in that directory, and -not- to 'copied' files. Is the actual action being taken by MEGA a true 'copy' command? That could explain what's going on with the ACLs not functioning. 

It's perhaps either that or MEGA is applying its own permissions, but the filesystem permissions should override any application permissions (as far as I know).

**Comment by polmr** [comment]
you can set permissions used for files created by MEGAcmd with `permissions -s 644 --files`. By default, those are 600 for files. See `permissions --help`.

**Comment by dersch** [comment]
G'morning @polmr 

Thank you very much for that information, it looks like it's working great now! I don't know why none of my googling managed to find that out, but I'm glad that that option exists. My temporary solution was to write a bash script that just kept adjusting permissions of everything every 5 seconds, but this is much better.

One follow-up, if that's alright:

How does Mega get around filesystem-level permission settings? I thought that those would go over an application-level setting. 


Thank you again.

**Comment by polmr** [comment]
Let's say that filesystem level permission mask affects to default opening of files. That does not prevent applications from setting different permissions when opening a file.

**Comment by dersch** [comment]
@polmr 

Understood, and thank you for the education! I hope you have a good day.
