### ISSUE TITLE
MEGAsync in Debian like Windows

### ISSUE THREAD

**Issue by PJL2k** [meganz/MEGAcmd#234]
Hello! Good afternoon!
First at all, thanks for the app and your continuous support!

I’ll let you know my current situation.
I’ve moved the place where I had the MEGA account from a Windows PC to a Debian (without Desktop, only Command Line).

I ran the mega-cmd command to login, so far so good, no issues here.
I ran the sync command for the first synchronization, here also, no issues.

And I added the following lines to the crontab file, but the files still doesn’t sync when I restart the computer o there is an issue with the electricity and the computer start again:

@reboot /usr/bin/mega-cmd
@reboot /usr/bin/mega-cmd-server
@reboot /usr/bin/mega-sync

Is there something that I missing?
I thought that the functionality in Debian would be the same as Windows.

Thanks a lot for reading me!

Kind regards!

**Comment by polmr** [comment]
you should only need to initiate `mega-cmd-server` at startup:
`mega-cmd` initiates an interactive shell that comunicates with the server (it initiates one if non is running)
`mega-sync` queries the server for active sync (your sync is configured already, no need to "list" it at startup.
I'm missing some `&` there at the end to have whatever process executed in the background. Also, you might want to add verbosity to see what's going on and redirect the log to a file. Something like: 
```
@reboot /usr/bin/mega-cmd-server --debug > /tmp/megacmd.log &
```
In any case, bear in mind that MEGAcmd is user dependent. Ensure that the cronttab you are editting is the user's, not root. And in the end you have a process named mega-cmd-server running as the user.

**Comment by PJL2k** [comment]
> 
> 
> you should only need to initiate `mega-cmd-server` at startup:
> `mega-cmd` initiates an interactive shell that comunicates with the server (it initiates one if non is running)
> `mega-sync` queries the server for active sync (your sync is configured already, no need to "list" it at startup.
> I'm missing some `&` there at the end to have whatever process executed in the background. Also, you might want to add verbosity to see what's going on and redirect the log to a file. Something like:
> 
> ```
> @reboot /usr/bin/mega-cmd-server --debug > /tmp/megacmd.log &
> ```
> 
> In any case, bear in mind that MEGAcmd is user dependent. Ensure that the cronttab you are editting is the user's, not root. And in the end you have a process named mega-cmd-server running as the user.

Thank you so much for your reply and solution!
I did it and it works as expected.
Thanks again!
Kind regards.
