### ISSUE TITLE
Task Scheduler Command Prompt poping up

### ISSUE THREAD

**Issue by stachu2k** [meganz/MEGAcmd#237]
I see Command Prompt with megacmd appearing every hour even when I'm not using it. I have found in Task Scheduler, that it is because of MEGAcmdUpdater.exe. Is it save to remove this task directly from Task Scheduler, because this command prompt popups became very annoying?

![scheduler](https://user-images.githubusercontent.com/6988196/63550895-f111f280-c533-11e9-9c7f-38c9c0d3f107.png)

![scheduler2](https://user-images.githubusercontent.com/6988196/63552187-50253680-c537-11e9-86ad-70152c2ae801.jpg)

**Comment by polmr** [comment]
That's strange. That should be run in the background. In any case, that's a mechanism to be able to update MEGAcmd in case there was an update that wouldn't boot the server. It's highly unlikely that that ever happens. You can safely remove @stachu2k

**Comment by stachu2k** [comment]
Thank you @polmr it worked.
