### ISSUE TITLE
Configure fails to recognize readline compiled from source

### ISSUE THREAD

**Issue by blazej222** [meganz/MEGAcmd#239]
Hello! I'm trying to cross compile MEGAcmd for my Raspberry pi. I'm currently on x64 Ubuntu machine, and have managed to succesfully builld arm-linux-gnueabihf compiler. I knew I needed dependencies, so firstly i tried downloading readline source from gnu site and compiling it using my cross compiler. Here are the commands I used to compile readline:

```
./configure --host=arm-linux-gnueabihf --prefix=`pwd`
make -j8
make install
```

Then I tried compiling MEGAcmd. I ran:

```
./configure --host=arm-linux-gnueabihf --with-readline=/home/vmware/Downloads/readline-7.0/ 
```

Unfortunately, configure script fails on 

```
checking readline/readline.h usability... yes
checking readline/readline.h presence... yes
checking for readline/readline.h... yes
checking for rl_save_prompt in -lreadline... no
configure: error: readline library is required for the sample client.
```

I've also tried extracting `/usr` `/opt` and `/lib` directories from my raspberry pi and copying them over to my build machine. I created folder called `/opt/sysroot/` and extracted all the files there, but when i run configure with `./configure --host=arm-linux-gnueabihf --with-sysroot=/opt/sysroot/` it fails to even find `readline.h` header.

@edit Can confirm MEGAcmd's configure fails even natively (on raspberry) using readline compiled and installed using make install directly on raspberry. Is there any difference between readline compiled from source and the one from raspbian repos?

**Comment by gabrielbse** [comment]
Same here, using Debian 10 to cross compile with host = --host=x86_64-w64-mingw32

```
checking readline/readline.h usability... yes
checking readline/readline.h presence... yes
checking for readline/readline.h... yes
checking for rl_save_prompt in -lreadline... no
```

**Comment by blazej222** [comment]
After some time I approached the problem again, trying to compile MEGAcmd with sysroot from my RPI3 with all required dependencies already installed. I've finally succeded with configure command:
 `./configure --host=arm-linux-gnueabihf --with-sysroot=/mnt/linux_hdd/sysroot LDFLAGS="-Wl,-rpath-link=/mnt/linux_hdd/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link=/mnt/linux_hdd/sysroot/lib/arm-linux-gnueabihf -latomic"`
What I believe was causing `lreadline` issue with readline compiled from source was a hardcoded libtool path - it forced the linker into looking for the library inside `/usr/lib/` directory on build PC instead of searching inside host sysroot. This problem is well documented [here](http://www.metastatic.org/text/libtool.html) and reading it might save somebody a lot of time! 
Please note that `--with-sysroot=` flag is probably not required if your cross-compiler was built with `--sysroot=` flag, I added it just to be safe.
Passing `-rpath-link` parameter in `LDFLAGS` is required, otherwise you will get dependencies error. Again, this is caused by linker trying to look for libraries inside build-PC's `/usr/lib`. This parameter overrides libraries path hardcoded inside `.so` files. This is a very similiar issue to the first one, but not exactly the same, as it's not about libtool's `.la` files but rather about `.so` files. It's very well documented [here](https://sysprogs.com/w/fixing-rpath-link-issues-with-cross-compilers/), but I wasn't able to fix it using their "universal solution" - I just passed required flags to the linker instead.
Finally, I had to add `-latomic` flag because for some reason the linker couldn't find a reference to `__atomic_load_8`.
