### ISSUE TITLE
How to stop sync for a specific localpath?

### ISSUE THREAD

**Issue by DanyGee** [meganz/MEGAcmd#257]
Hi,

what is the correct statement to **stop a sync** like this one below?
`sync /home/user/localfolder /remotefolderonmega`

I simply want to remove some established sync's to free up some space on one of my machines.

**Comment by polmr** [comment]
`sync -d /home/user/localfolder` would delete the synchronization (not the data)
`sync -s /home/user/localfolder` would stop/pause the synchronization
Further info: `sync --help`

**Comment by DanyGee** [comment]
THX!

**Comment by RizwanPascalineSoft** [comment]
Hi,
 polmr
what is the correct statement to stop a sync like this one below? i am facing same issue i use the following method but its not work for me. when i run this command its show an error its already exist. how to delete my sync ?
sync -d /home/user/localfolder would delete the synchronization (not the data)

**Comment by RizwanPascalineSoft** [comment]
> `sync -d /home/user/localfolder` would delete the synchronization (not the data) `sync -s /home/user/localfolder` would stop/pause the synchronization Further info: `sync --help`

its not work for me any other suggesion please

**Comment by RizwanPascalineSoft** [comment]
> `sync -d /home/user/localfolder` would delete the synchronization (not the data) `sync -s /home/user/localfolder` would stop/pause the synchronization Further info: `sync --help`

@polmr

**Comment by RizwanPascalineSoft** [comment]
> > `sync -d /home/user/localfolder` would delete the synchronization (not the data) `sync -s /home/user/localfolder` would stop/pause the synchronization Further info: `sync --help`
> 
> its not work for me any other suggesion please

@polmr

**Comment by polmr** [comment]
> what is the correct statement to stop a sync like this one below? 

Which one?

Note that currently, `mega-sync` also lists an ID (first column).
e.g:
```
ID          LOCALPATH   REMOTEPATH ACTIVE  STATUS  ERROR SIZE     FILES DIRS   
9gKbw9SbBqk /local/path /remote/path    Enabled Syncing NO    68.39 MB 24    8   
```
You can also remove a sync with:
```
mega-sync -d 9gKbw9SbBqk
```
