### ISSUE TITLE
megaclient.exe config file

### ISSUE THREAD

**Issue by cezar-pimentel** [meganz/MEGAcmd#259]
Hello guys!

Is there a way to run megaclient.exe passing an argument to a config file location, where I can set (inside this config file) a specific number of upload workers, username and password?

I saw some examples on some websites, but megaclient.exe doesn't seem to understand that argument.

Thanks in advance.

**Comment by polmr** [comment]
You might be referring to another megacmd. The official MEGAcmd features a server and two kids of clients: one interactive (MEGAcmd shell) and another non-interactive (megaclient.exe in Windows). You don't need a config file to store user/pass. MEGAcmd server saves your session once you are logged in. Everything should be explained here: https://github.com/meganz/MEGAcmd/blob/master/README.md .

**Comment by cezar-pimentel** [comment]
Hello polmr. Thanks for your reply.
Indeed, everything you said is true.

But, what I really wanted was to upload two files simultaniously. Is that possible when using megacmd? If so, can you tell me how or send the propor documentation link?

Thanks again.

**Comment by polmr** [comment]
Hi @cezar-pimentel . You can queue as many files to upload as you want (passing `-q` to `put` command: https://github.com/meganz/MEGAcmd/blob/master/UserGuide.md#put). The uploads are done _more or less in sequence_ though (but with parallel connections to ensure a proper throughput).

**Comment by cezar-pimentel** [comment]
Yes, that's what my code does.
I use "-q" and it queues the files, but the second file is sent only when the first queued upload finishes. What I wanted was to send both files concurrently.
Is that possible?
Thanks

**Comment by polmr** [comment]
No. But there's no real advantage in that: the uploads already run in parallel connections to ensure a proper throughput.

**Comment by cezar-pimentel** [comment]
> No. But there's no real advantage in that: the uploads already run in parallel connections to ensure a proper throughput.

No problem. Thanks for the reply.

Cheers!

👊
