### ISSUE TITLE
MEGAcmd sync import

### ISSUE THREAD

**Issue by cdenneen** [meganz/MEGAcmd#268]
You can currently use the GUI MEGAsync to configure existing MEGAsync to a local folder but as it stands `mega-sync` only allows local -> remote from scratch.
It complains about already exists and also the second parameter is supposed to be local path but appears to error about remote path:

```
Usage: sync [localpath dstremotepath| [-dsr] [ID|localpath]
~ » mega-sync MEGAsync .megasync
[err: 19:26:19] Couldn't find remote folder: .megasync
~ » mega-sync MEGAsync MEGAsync
[err: 19:30:24] Failed to sync folder: Already exists
~ » mega-sync .megasync MEGAsync
[err: 19:33:48] Failed to sync folder: Already exists
```

I would like the ability to sync from remote to local on new machines using MEGAcmd.

**Comment by mattw-mega** [comment]
The root folder of the sync must exist (on remote or local, whichever direction you are syncing) before running the `mega-sync` command.   Please try `mkdir MEGAsync` then `mega-sync MEGAsync MEGAsync`  thanks.

**Comment by mattw-mega** [comment]
Please try using fully qualified paths to ensure the program is lookiing in the correct directories - eg (and this is from within megacmd on windows:
```ABC@XYZ:/$ sync c:\tmp\.newsync /mycloudpath/mynewsync
ABC@XYZ:/$ sync
ID LOCALPATH                                                            REMOTEPATH                                                           ActState   SyncState     SIZE  FILES   DIRS
 0 \\?\c:\tmp\.newsync                                                  /mycloudpath/mynewsync                                               Active     Synced      0.00 B      0      0 ```

**Comment by cdenneen** [comment]
Same issue:

```
ABC@XYZ:/$ sync /Users/cdenneen/.megasync MEGAsync
[err: 16:26:59] Failed to sync folder: Already exists
ABC@XYZ:/$ sync
ID LOCALPATH        REMOTEPATH       ActState   SyncState     SIZE  FILES   DIRS
 0 /Users.../.certs /MEGAsync/certs  Active     Synced    100.77 KB     65      0
ABC@XYZ:/$ sync /Users/cdenneen/.megasync /MEGAsync
[err: 16:28:38] Failed to sync folder: Already exists
ABC@XYZ:/$
```

**Comment by mattw-mega** [comment]
Ah, I see - you already have a sync set up on /MEGAsync/certs.   MEGAsync doesn't allow setting up a sync folder that contains another already synced folder, that's what it's complaining about.  Your outer folder would be sufficient to sync that inner folder to the cloud, so you can cancel the existing sync, and then the creation of the new one should succeed.  cheers
