### ISSUE TITLE
Concurrent file download..

### ISSUE THREAD

**Issue by intern0t** [meganz/MEGAcmd#290]
Is there any concurrency feature available? For example, downloading 2-3 files at once rather than 1 by 1.

**Comment by polmr** [comment]
you can pass `-q` to `get` command to enqueue multiple downloads. see `get --help`

**Comment by intern0t** [comment]
@polmr I believe `mega-get -q` simply adds it to the queue rather than download multiple at a time. I believe parallel download would be the proper term for what I am referring to. It would definitely speed things up, I think. For example, downloading 4-5 files at once rather than 1 by 1, etc.

**Comment by polmr** [comment]
aham... files are actually downloaded in multiple parallel connections (6 if I recall correctly) that download files parts concurrently. For small files or at the end of the download of a file you might even have multiple files being downloaded simultaneously. MEGAsync allows configuring that number, we might want to let MEGAcmd configure those too. But in principle the default parallel number of connections should maximize throughput already.

**Comment by intern0t** [comment]
Ohh, I didn't know that option existed. If I could tell MEGAsync to download a certain number of files at a time, that would be amazing.

**Comment by anasty17** [comment]
Hi, not added yet ? Like if I'm downloading 50 gb file and i want download 100mb file. I should wait first download to finish ?

**Comment by sam-roberts** [comment]
@polmr hopefully not necroing this thread-  so in the case where I log mega-transfers, I will only see 1 file being downloaded at a time, but if I'm understanding you correctly, that behaviour is expected because that "1 active" is achieving maximum throughput already through multiple connections?
