### ISSUE TITLE
Missing mega-* binaries

### ISSUE THREAD

**Issue by danielandross** [meganz/MEGAcmd#294]
When building with latest sources on debian 9 as described here. There is only megacli and megasimplesync. I am missing mega-get. What am I doing wrong? How do I get the non-interactive mega-get?

**Comment by mattw-mega** [comment]
`mega-get` is part of MEGAcmd, which has the SDK as a dependency.  You can get that project at:  https://github.com/meganz/MEGAcmd

**Comment by mattw-mega** [comment]
`mega-get` is a wrapper script that invokes `mega-exec`.  You can find it here: https://github.com/meganz/MEGAcmd/tree/master/src/client

**Comment by danielandross** [comment]
My mistake at build.  It works if you do it step by step as explained here.
Thank you for response and your great software.
