### ISSUE TITLE
mega-find -mtime not working

### ISSUE THREAD

**Issue by bgi** [meganz/MEGAcmd#30]
It seems as mega-find with mtime is not working:

I got files from Match 13th and Match 14th. 
When I do mega-find -mtime='-1d' I get nothing.
When I do mega-find -mtime='+1d', I get all files, those form 13th and from 14th.

Any help is appreciated.

**Comment by polmr** [comment]
Hi @bgi, that's indeed a bug. That functionality seem to be broken due to some changes introduced ~4 months ago, thanks for reporting that. We'll fix it asap.

**Comment by bgi** [comment]
please update the thread when there is a patch.
Can I expect the x64 RPM package to be updated too?

Thanks

**Comment by bgi** [comment]
@polmr any other way to get the modified or creation date of files?

**Comment by polmr** [comment]
https://github.com/meganz/MEGAcmd/commit/e21f972ea73d7b5f72b1530c7dd2a77d475a0dd6 should solve this. Will release new packages soon.
And no, currently there's no way to see that. You need to use the `webclient` for the moment. There will be improvements in "ls" to have such times and all extra info with better formatting.

**Comment by bgi** [comment]
@polmr, give my a hint and I try to expand the ls command. this feature would be so awesome
Thanks for the patch

**Comment by bgi** [comment]
How can I compile only the cmd?

**Comment by polmr** [comment]
Instructions are here: https://github.com/meganz/MEGAcmd . let us know if you find any issue

**Comment by bgi** [comment]
when I downloaded the megacmd source as a zip, the sdk folder was empty autoconf needed some file from there, so I had to get the sdk folder from the megasdk github page, I also had to search and install quite a few apckeages for centos, I will list them here when Im done. also I had to compile cryptopp the version you posted in the other thread, gues it was 5.6.5 the version 6.* didnt compile.

**Comment by bgi** [comment]
Im stuck here:

configure: error: Make sure cURL is built/linked with OpenSSL!
configure: error: ./configure failed for sdk

I tried curl compile with:
./configure --enable-ssl & make & sudo make install
./configure --with-ssl=/usr/bin/openssl  & make & sudo make install
./configure --with-ssl=/usr/local/openssl & make & sudo make install

After every trial I did make uninstall.

Cant you just make a new RPM package?

**Comment by polmr** [comment]
Here you have an [adhoc package ](https://github.com/meganz/MEGAcmd/files/1817347/megacmd_cento7fixtimes.zip) for you to use. Hopefully it'll due until we release a new version for everyone to use

**Comment by bgi** [comment]
works! thank you very, very much!!!

**Comment by polmr** [comment]
This has been fixed in version 0.9.9
