### ISSUE TITLE
Megacmd .bat comand Mega-put killing cmd

### ISSUE THREAD

**Issue by MrVtR** [meganz/MEGAcmd#303]
Hello,I'm using mega-put and mega-export comand on a .bat file,as soon as the .bat activate the mega-put and finish,it kills the cmd and doesn't execute mega-export or other command below of the mega-put,even with "pause" command,it kills the cmd.
Someone knows what's the problem?

Sample code:
mega-put sample.zip /
mega- export -a sample.zip

The file is uploaded to my cloud with mega-put command, but any command below that is not executed by the .bat file

**Comment by mattw-mega** [comment]
mega-put and mega-export are in fact wrapper scripts themselves, so from a batch file you need to use the CALL keyword.   eg.
CALL mega-put sample.zip /
CALL mega- export -a sample.zip

**Comment by MrVtR** [comment]
Thanks @mattw-mega ,worked here,problem solved!
