### ISSUE TITLE
MEGAcmd script not work from CMD batch file

### ISSUE THREAD

**Issue by arlido** [meganz/MEGAcmd#311]
I want o use MEGAcmd script in my batch file (CMD scipt). Everything in that batch works well, but MEGAcmd scipt not. It looks like this:

```
SET PATH=C:\Users\PC_USER\AppData\Local\MEGAcmd;%PATH%
mega-login mail password
mega-cd my-backup
mega-put E:\BACKUP_TEMP
mega-logout
```

When i open it from .bat file I see login line and after some while window closed and nothing happen after that. But when i open CMD from start menu and paste in that windows this script line by line everything works good. Also when I create 3 separate bat files and open it one by one also everything works. Why, what I'm, doing wrong?

Thanks for help

**Comment by mattw-mega** [comment]
try putting CALL before the mega-login and other mega-* commands, as those are batch files forwarding the request to mega-exec.

**Comment by arlido** [comment]
Thanks a lot. This works fine now.
