### ISSUE TITLE
backup 'e'stablished string mispelt.

### ISSUE THREAD

**Issue by RevoluPowered** [meganz/MEGAcmd#32]
> execute this command in mega-cmd on linux / centos 7 (version: using latest rpm package from mega.nz)

backup /somefolder /megafolder/subfolder/ --period="0 0 0 4 * * *" --num-backups=10

Minor spelling error on output.
**output:** backup stablished: /blah/ period ="0 0 4 * * *" Number-of-Backups=10
**expected:** backup established: /blah/ period ="0 0 4 * * *" Number-of-Backups=10

**Comment by polmr** [comment]
thanks for pointing that out @RevoluPowered, It'll be corrected in the next release

**Comment by polmr** [comment]
This has been fixed in version 0.9.9
