### ISSUE TITLE
sync not working on windows

### ISSUE THREAD

**Issue by itziksi** [meganz/MEGAcmd#324]
Hi,
I've installed MEGAcmd, but "sync" command not working.
It doesn't show any error, even with "mega-log -s verbose" and "mega-log -c verbose".
I put wrong folder names on purpose to check if error work
 and then it shows error for wrong folder name, so problem is not folder names.
I also tried remove files from "\user\AppData\Local\Mega Limited",
and this didn't help.
No log in output, no error, but also doesn't work...
Any idea is appreciated, including any more files I can delete to cause db to get "refreshed"
Thanks.

**Comment by polmr** [comment]
Currently `sync` is lacking a success message. Configuring a sync with 
```sync C:\local\path /remote/path``` and then issuing `sync` without parameters should list the sync and it's status ... doesn't it?
Can you try to use it passing `-vv` to the aforementioned commands, to see some logging messages (if any)?
MEGAcmd stores data in `${AppData}\Local\MEGAcmd\.megaCmd` in Windows: 
there you can find a file named `syncs` that control the configured syncs, plus local caches, and all configurations.
Btw, your issued log commands increase the verbosity of MEGAcmdServer, not in the client side. More on debugging here: https://github.com/meganz/MEGAcmd/blob/master/contrib/docs/DEBUG.md#windows

**Comment by itziksi** [comment]
Hi polmr, thanks for your help.
I've started the server with --debug-full (Windows), and now I can see the logs.

1) I think the problem with the sync is as follows,
this the script I use:
mega-login
mega-sync A B
mega-logout

Is it possible, that mega-logout terminates the sync, so not all files are synced ?
If so, how can I know from command line, when sync has finished, so I can call logout ?
    
2) I excepted MEGAcmdServer.exe to be passive, but I see it syncs automatically.
Namely if I call "sync A B", will sync it only once,
will it continue to sync it as long as the server process is running,
or it will continue to sync it from now on ?
What I see now is:
I call "sync A B", then quit server, delete folder A.
When I run the server again, folder A is restored automatically.
I have the GUI still installed,  but I dont use.
Where is this configured ?
(which folder are automatically synced)
Thanks for your help,
Si.

**Comment by polmr** [comment]
> Is it possible, that mega-logout terminates the sync, so not all files are synced ?
Yes, logout terminates the sync.
If so, how can I know from command line, when sync has finished, so I can call logout ?
`sync` command (with no arguments) gives you the status of the configured synchronizations:
```
ID LOCALPATH     REMOTEPATH ActState SyncState SIZE    FILES DIRS              
0  A             B          Active   Synced    0.00  B 0     1   
```
`Synced` is the key to know when a synchronization is done. 

> I excepted MEGAcmdServer.exe to be passive, but I see it syncs automatically.
Namely if I call "sync A B", will sync it only once,
will it continue to sync it as long as the server process is running,
or it will continue to sync it from now on ?

It will establish a two-way synchronization between A and B. The synchronizaton (file transfering, and removal) will be carried out as long as MEGAcmd Server is running. 
If the server is close, the synchronization will be resumed when MEGAcmd Server is opened again (as long as you haven't `logged out`)

> I have the GUI still installed, but I dont use.
Where is this configured ?
Are you referring to MEGAsync? MEGAsync & MEGAcmd are completely different products. Each of them have a sync engine, that allow for you to establish syncs between local folders and remote paths in MEGA. 
> (which folder are automatically synced) In MEGAsync you can see the synchronizations configured in Syncs tab in the app settings. In MEGAcmd, by typping `sync`. Bear in mind that you should not sync the same paths with MEGAsync or MEGAcmd: you don't want two sync engines competing against each other. That also applies to syncs with other vendors.

**Comment by itziksi** [comment]
I'm pretty sure it was the mega-logout.
At first it caused the sync to terminate,
and then when I removed to see if sync works without it,
it caused the "auto sync".
It would very useful if you could add some way of notification in the MEGAcmd,
if calling logout cause sync to terminate.
Thanks for your time and help
