### ISSUE TITLE
Error starting request: -2

### ISSUE THREAD

**Issue by forescat** [meganz/MEGAcmd#326]
What a mistake on log file? 
[info: 19:45:25] Added backup: /data/samba/transfer to /1for1/data/backup
[API:err: 19:45:47] Error starting request: -2 

Linux ubuntu 16.04 server
console mega-cmd witch root access

**Comment by polmr** [comment]
`-2` indicates an error in arguments in some request. May you increase log level (see `log --help` or `debug`), the source of the error might be clearer.

**Comment by forescat** [comment]
"Error starting request: -2" error was called due to 
bad non utf-8 directory name.
Thanks
