### ISSUE TITLE
get command not working 

### ISSUE THREAD

**Issue by aswathm78** [meganz/MEGAcmd#33]
I'm trying to download a large size file to a remote server . But Whenever I use mega-cmd and get command, I get error as **Blocked** 

`[err: 03:51:21] Download failed. error code:Blocked`

**Comment by polmr** [comment]
That error means that your account has been blocked. Login in the [webclient](https://mega.nz) if you want to see the reasons.

**Comment by aswathm78** [comment]
Thanks for the support ! I will proceed with site's official support !!!

**Comment by adityasethCSEK** [comment]
Hi, My Account is not locked as I can still download files using the web interface but whenever I try to do a get I get the same error message
