### ISSUE TITLE
Attributes like free space and total available via the scriptable batch files?

### ISSUE THREAD

**Issue by elmstreetvictim** [meganz/MEGAcmd#342]
Am I missing something or is my only way of finding the available space and used space using the whoami or du commands and then trimming and parsing the output in order to obtain these values?

**Comment by polmr** [comment]
`df --help` will help you ;-)

**Comment by elmstreetvictim** [comment]
Thank you. But it looks like I will need to capture and parse this info programmatically. I am closing this issue. Thanks again
