### ISSUE TITLE
Hidden Autostart on Windows

### ISSUE THREAD

**Issue by c0deing** [meganz/MEGAcmd#345]
is there any way to Start MegacmdServer/Shell in the Background on
startup in Windows (without seeing the command line?)?
If i put the MegacmdShell.exe/server.exe into autostart, i see the
command line on every startup; Is there any way to start it "hidden" in
the Background, so it will run every time i start my pc and perform the
backups defined?

**Comment by polmr** [comment]
This might help: create an `startMEGAcmdServer.vbs` script with the contents:
```
Dim WinScriptHost
Set WinScriptHost = CreateObject("WScript.Shell")
WinScriptHost.Run Chr(34) & "C:\Users\YOUR_USER_NAME\AppData\Local\MEGAcmd\MEGAcmdServer.exe" & Chr(34), 0
Set WinScriptHost = Nothing
```
Note: you need to fix that path to your `MEGAcmdServer.exe` path .

**Comment by c0deing** [comment]
I followed your instructions and so far its working as expected. Thank you very much for your help! :)
