### ISSUE TITLE
How to  cd  to a public folder's link and choose files

### ISSUE THREAD

**Issue by takifouhal** [meganz/MEGAcmd#351]
I want to access files (choose what to import or download) from a publicly available folder 
`mega-cd https://mega.nz/folder/id#key`
and with `mega-get` it will download the whole folder.
I want to explore it first then choose what files to pick.

**Comment by polmr** [comment]
For the moment, the only way to browse files within a public link is to log into it (but you would need to first logout from your account):
```
mega-login https://mega.nz/folder/id#key
```
Then, there's a rather intricate way to get downloadable links:
```
you can pass `--show-handles` to `ls` or `find` commands, and get the handle of the file/folder you wish to download (it'll be something like `<H:XXXXXX>`. You can append that handle `XXXX` to the original folder link and get direct links to subfoler/subfiles:
```
mega-get https://mega.nz/folder/id#key/file/H:XXXXXX
```
We will add support for browsing folder links without needing to log into them and ease the above process.
Notice that you can always get links like the one above for MEGAcmd to digest, using the web client.
