### ISSUE TITLE
Use MEGAcmd for a MEGAdrop folder

### ISSUE THREAD

**Issue by matheograil** [meganz/MEGAcmd#355]
Hi,
I would like to know how to upload a file in MEGAdrop folder with MEGAcmd ?
Thanks !

**Comment by GamingWessel** [comment]
From the documentation:
```
Login
Log into your MEGA account (example)

Usage: login [email [password]] | exportedfolderurl#key | session

You can log in either with email and password, with session ID, or into a folder (an exported/public folder).
If logging into a folder indicate url#key
```
You will need the folderurl and key

**Comment by dennisheer** [comment]
How did you manage to upload a file to a MEGAdrop folder using MEGAcmd, @matheograil?

This doesn't work for me. Neither for a MEGAdrop folder nor for a public folder. Here's what I've tried:

## MEGAdrop folder
- Login to the MEGAdrop folder fails:

        $ login <MEGAdrop_URL>
        [API:err] Failed to Login: Invalid argument

- Uploading directly to the MEGAdrop folder _without_ being logged in fails:

        $ put <FILEPATH_LOCAL_FILESYSTEM> <MEGAdrop_URL>
        [API:err] Not logged in.

- Logging in to my personal account and then trying to upload to the MEGAdrop folder fails:

        $ login <EMAIL_ADDRESS>
        […]
        [API:info] Login complete as <EMAIL_ADDRESS>

        $ put <FILEPATH_LOCAL_FILESYSTEM> <MEGAdrop_URL>
        [API:err] Couln't find destination folder: <MEGAdrop_URL>. Use -c to create folder structure

- Using the `-c` flag fails with the same error, but creates a folder structure according to the `<MEGAdrop_URL>' in my root directory on MEGA:

        $ login <EMAIL_ADDRESS>
        […]
        [API:info] Login complete as <EMAIL_ADDRESS>

        $ put -c <FILEPATH_LOCAL_FILESYSTEM> <MEGAdrop_URL>
        [API:err] Couln't find destination folder: <MEGAdrop_URL>. Use -c to create folder structure

## Public Folder
- Uploading after logging in to the folder fails:

        $ login <PUBLIC_FOLDER_URL>

        $ put <FILEPATH_LOCAL_FILESYSTEM>
        [API:err] TRANSFERRING ||########################################################################||(0/0 KB: 100.00 %) 
        Failed to upload: Access denied

- Uploading directly to the public folder _without_ being logged in fails:

        $ put <FILEPATH_LOCAL_FILESYSTEM> <PUBLIC_FOLDER_URL>
        [API:err] Not logged in.

- Uploading after logging in to my personal account fails:

        $ login <EMAIL_ADDRESS>
        […]        
        [API:info] Login complete as <EMAIL_ADDRESS>

        $ put <FILEPATH_LOCAL_FILESYSTEM> <PUBLIC_FOLDER_URL>
        [API:err] Couln't find destination folder: <PUBLIC_FOLDER_URL>. Use -c to create folder structure

- Using the `-c` flag fails with the same error, but creates a folder structure according to the `<MEGAdrop_URL>' in my root directory on MEGA:

        $ login <EMAIL_ADDRESS>
        […]        
        [API:info] Login complete as <EMAIL_ADDRESS>

        $ put <FILEPATH_LOCAL_FILESYSTEM> <PUBLIC_FOLDER_URL>
        [API:err] Couln't find destination folder: <PUBLIC_FOLDER_URL>. Use -c to create folder structure

By `PUBLIC_FOLDER_URL` I mean a MEGA folder that is shared via a URL with an integrated decryption key.

**Comment by csBlueChip** [comment]
I too would like to know how this was resolved.

MegaDrop folders do NOT have a link in the format url#key
To "get a link" in the format url#key, you MUST disable MegaDrop, and switch to a Public folder

I wish to write a script to backup my picture database each day - but I do NOT want to store my Mega credentials on the database server.

Is someone able to provide a single working example of uploading to a "MegaDrop" folder (without logging in) please? ...EG. If I have the file `/home/user/database.sql` and I wish to store it in the MegaDrop folder `https://mega.nz/megadrop/jTSlyH5Fd2g` what `mega-*` command would I enter at the shell prompt?

Thanks,
BC
