### ISSUE TITLE
Unable to sync with Synology

### ISSUE THREAD

**Issue by nerzki** [meganz/MEGAcmd#359]
So, I am trying to sync a folder on my mega and my NAS. Installed MegaCMD on my NAS and I am able to SSH but when I try to use the command sync or get, nothing happens. Keeps telling me "couldn't find file/folder". I tried using MegaCMD on Windows and initiated the same command and was a success. So I was so sure its not the command but the megacmd on my NAS. I hope someone can shed some light on this. Appreciate any help. Thanks!

**Comment by mattw-mega** [comment]
Here's a quick example on Synology ( I see it had a record of an old sync too, please ignore that one)
```admin@MEGA-DS218j:~$ mkdir test3
admin@MEGA-DS218j:~$ mega-sync ./test3 /test3
admin@MEGA-DS218j:~$ mega-sync
ID LOCALPATH                     REMOTEPATH ActState SyncState SIZE    FILES DIRS
0  /volume1/homes/admin/MEGAsync NOT FOUND  Disabled Ignored   0.00  B -1    -1
1  /volume1/homes/admin/test3    /test3     Active   Synced    5.00  B 1     0
admin@MEGA-DS218j:~$```
