### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by in-in** [meganz/MEGAcmd#36]
The Readme section ‘Usage examples’ do not contain any examples of how to login

This line `login email password | exportedfolderurl#key | session` from `mega-login –help` command is not clear to me. I do not have a login, in `MegaSync` I use email and password.

But this command `mega-login example@example.com password123` does not work

**Comment by polmr** [comment]
`mega-login example@example.com password123` is the way to go in non-interactive mode. There might be some issues with non-ascii characters if you are using windows. What's the output of mega-login command?  Perhaps we might want to include a brief tutorial with screenshots to illustrate the most basic straight-forward use-cases.

**Comment by in-in** [comment]
I use Ubuntu 16.04 and the output is `quote>`
And my password has special characters, such as "*" or "<"

>Perhaps we might want to include a brief tutorial with screenshots to illustrate the most basic straight-forward use-cases.

It will be great.
I thought I could use _megacmd_ on my old laptop to reduce the consumption of resources and I thought that the program would also work like _megasync_.

But I don't know if _megacmd_ can watch my file and run sync action automatically like _megasync_ or should I write some script for this purpose

**Comment by in-in** [comment]
I tried `mega-login example@example.org "password"` and it didn't work the output was `dquote>`

And I also tried `mega-cmd` then `login example@example.org password` it did not work the output was "Login failed: invalid email or password"

I thought that there was some secret to login. That's why I asked the question.

But now I tried `mega-cmd` then `login example@example.org "password"` and successfully logged in

Thank you

**Comment by sebastianwestberg** [comment]
The above happened to me as well. Follow

> I tried `mega-login example@example.org "password"` and it didn't work the output was `dquote>`
> 
> And I also tried `mega-cmd` then `login example@example.org password` it did not work the output was "Login failed: invalid email or password"
> 
> I thought that there was some secret to login. That's why I asked the question.
> 
> But now I tried `mega-cmd` then `login example@example.org "password"` and successfully logged in
> 
> Thank you

Had problems with this as well: `Login failed: invalid email or password` but then i tried the interactive `mega-cmd` command as you suggested and it worked perfectly.

**Comment by c-edw** [comment]
I have had issues with `mega-login` too, but even if it did work, passing credentials as parameters is a bad idea. On most Linux distributions, they'll be logged to a shell history file. It should take the username/email as a parameter and then prompt for a password.

**Comment by Seversonic** [comment]
You can login this way non-interactively this way
mega-login example@example.org 'password123'

put your password in single quotes and you're on your way

**Comment by dkuchay** [comment]
Mega-login still does not work. This is a users guide for advanced users who already know the basics. Where is the getting started or quick start? To obscure basic features away from the guide makes no sense. Same issue as everyone else here. My password has an exclamation point in it and that is the point of breaking "event not found". Even with quotes i get unexpected returns from mega-login. Arch linux current at date of posting. Please update basic functionality in to the guide and add special characters to login strings.

**Comment by 524c** [comment]
Opensource projects manage to have excellent applications, and this commercial manages to be so horrible, limited documentation done, terrible.

**Comment by 524c** [comment]
Open source projects manage to have excellent applications, and this commercial manages to have such horrible and limited documentation.

**Comment by therealOri** [comment]
For if anyone is still having issues and need a more clear explanation.
__ __

<br>
<br>

For `mega-cmd` the format is the following;
`mega-cmd email "password"`
> If you have 2fa enabled
> `mega-cmd --auth-code=123456 email "password"`
__ __

<br>

And for the `mega-login` command, it is as follows;
`mega-login email 'password'`
> If you have 2fa enabled
> `mega-login --auth-code=123456 email 'password'`
__ __
> The difference is the quotes used. `""` and `''`.

**Comment by akademy** [comment]
The safest way to log in appears to be:

`mega-cmd`

then:

`login <email-address>`

And then it will ask you to input the password without echoing it to the command line. This is to avoid it appearing in a log/history file...

(This worked for me in Fedora Linux, megaCmd v1.7.0.21)
