### ISSUE TITLE
Limited documentation examples on mega-backup with cron-expressions....Invalid Arguement...HELP?

### ISSUE THREAD

**Issue by Danrancan** [meganz/MEGAcmd#369]
I am trying to use a non-interactive command to back up a folder every Sunday at 3:30AM. I am not understanding why cron expressions are giving me an "Invalid Arguments" error. For example, in a regular crontab, if I wanted to schedule a backup Every Sunday at 3:30AM, I would enter the following command after logging in:
`mega-backup /home/user/backupfolder /Megabackupfolder --period="0 30 3 ? * SUN *" --num-backups=20`
However, When I try this command, I get the error: Failed to establish backup: Invalid argument.
Does anyone have any clue on how to fix this or where I can find more resources on understanding cron expresssions properly to fix it myself? Please let me know! I am a noob. Thanks!

**Comment by aabellagm** [comment]
Hi @Danrancan 

With `mega-backup --help` (or `backup --help` in the interactive session) you can see the format of the cron like expression for the --period parameter. Note it is in UTC.
```
     Cron like period is formatted as follows
      - - - - - -
      | | | | | |
      | | | | | |
      | | | | | +---- Day of the Week   (range: 1-7, 1 standing for Monday)
      | | | | +------ Month of the Year (range: 1-12)
      | | | +-------- Day of the Month  (range: 1-31)
      | | +---------- Hour              (range: 0-23)
      | +------------ Minute            (range: 0-59)
      +-------------- Second            (range: 0-59)
```
For every Sunday 3:30 AM (UTC), the format is "0 30 3 * * 7"

You can find more info about backups here too [BACKUPS.md](https://github.com/meganz/MEGAcmd/blob/master/contrib/docs/BACKUPS.md)
