### ISSUE TITLE
Need auto-complete [ZSH]

### ISSUE THREAD

**Issue by rajeshisnepali** [meganz/MEGAcmd#372]
My primary shell is zsh (oh-my-zsh) and I can not find any auto complete for command ran outside `mega-cmd` shell (non-interactively).

I tried changing `zsh` to `bash` and worked fine. 
Need auto-complete for ZSH shell too.
Thanks.

**Comment by aabellagm** [comment]
Hi,
Sadly, we currently have no plans to add autocomplete for Zsh shell.
