### ISSUE TITLE
Missing *.deb builds for Raspbian

### ISSUE THREAD

**Issue by morozov** [meganz/MEGAcmd#376]
The latest available [packages for Raspbian 9.0](https://mega.nz/linux/MEGAsync/Raspbian_9.0/arm/) and 10.0 (probably, other distros too) are 1.1.0 while the latest released version for Linux is 1.2.0.

**Comment by aabellagm** [comment]
Hi @morozov,

We are working on it, packages for Raspbian 9.0 and 10.0 will be updated in the next days.

Thanks for pointing it!

**Comment by morozov** [comment]
Thanks, @aabellagm. I can see the packages are now [available](https://mega.nz/linux/MEGAsync/Raspbian_9.0/armhf/).
