### ISSUE TITLE
[MegaCMD] Webdav error: Command not found

### ISSUE THREAD

**Issue by f14a2cd** [meganz/MEGAcmd#395]
Debian 9, 64 bit.
When mega configured successfully, i can log in my mega account, but i can't call webdav command.
It shows:
```
root:~# mega-webdav /
[API:err: 06:49:35] Command not found: webdav
```
Configure command:
`./configure && make install`
MEGA version: `MEGAcmd version: 1.2.0.0: code 1020000`

How can I enable this feature?

**Comment by f14a2cd** [comment]
Yay! Problem was solved using official deb package. (it's not a full solution, but can be valid as a hot-fix).

**Comment by dony71** [comment]
I have same issue.
@f14a2cd : how you resolve using official deb package ?

**Comment by WammKD** [comment]
Same here; it seems clear it's possible to compile MEGAcmd without functioning webdav support.

I'm using MEGAcmd off of Guix; the version in the repo.s is 1.1.0 but, concerned that my webdav issues were related to version, I built a package for 1.5.1 and installed that but had the same experience.

It builds fine, without error, and everything seems to work fine, other than webdav – I get the same output of "Command not found: webdav".

Is there a dependency that's particularly required for webdav functionality to work? I think the Guix package is installing all listed dependencies in the README.

**Comment by polmr** [comment]
libuv is the particular dependency required by the webdav specific code.

Guix package seem to be compiled [without it](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/sync.scm?id=abd6ea5337079654ad2dba05538bf6e7d9051c4d#n214:~:text=(inputs%0A%20%20%20%20%20%60((%22c%2Dares,sqlite)%0A%20%20%20%20%20%20%20(%22zlib%22%20%2Czlib))))

If you were to compile it yourself, autoconf needs to find it in your system and place 
```
#define HAVE_LIBUV 1
```
at `./sdk/include/mega/config.h`

**Comment by WammKD** [comment]
Thanks a ton, @polmr; as usual, your specificity is a godsend. It'd be good to get the version updated, to begin with, so I can roll this in, as well, and get a more robust MEGAcmd into the repo.s.

Thanks, again!
