### ISSUE TITLE
mega-sync not detecting file changes

### ISSUE THREAD

**Issue by kwatson** [meganz/MEGAcmd#397]
Hello,

I'm having a frustrating issue where `mega-cmd-server` does not appear to be detecting _any_ file changes after the initial startup & scan process.

On first boot, `mega-cmd-server` correctly identifies local/remote changes and syncs, however once the process is running, any changes (additions or deletions) will not be detected.

The directories i'm syncing are attached via smb (cifs) -- is it possible that sync just isn't being notified of those changes? If `mega-sync` depends on those OS notifications, is it possible to config an automatic periodic poll for file changes?

```
$ mega-sync
ID LOCALPATH      REMOTEPATH     ActState  SyncState  SIZE        FILES  DIRS
0  /documents     /Documents     Active    Synced     138.96 GB   11854  873
1  /backup        /Backup        Active    Synced     3.26 TB     8513   912
```

I ran `mega-cmd-server` with `--debug-full` and the only thing I see after the intial startup scan is:

```
[API:debug: 22:26:55] Removing socket 39
[API:debug: 22:26:55] CURLMSG_DONE with HTTP status: 200 from g.api.mega.co.nz - 31.216.147.132
[API:debug: 22:26:55] sc Received 1: 0
[API:debug: 22:26:55] SC keep-alive received
[API:debug: 22:26:55] DNS cache hit for g.api.mega.co.nz (IPv4) 31.216.147.132
[API:debug: 22:26:55] sc POST target URL: https://g.api.mega.co.nz/wsc/...
[API:debug: 22:26:55] sc Sending 0:
[API:debug: 22:26:55] Using the IP of the hostname: 31.216.147.132
[API:debug: 22:26:55] Set cURL timeout[2] to 106329 ms from 0
[API:debug: 22:26:55] Disabling cURL timeout
[API:debug: 22:26:55] Adding/setting curl socket 39 to 1
[API:debug: 22:26:55] Set cURL timeout[2] to 106329 ms from 0
[API:debug: 22:26:55] Disabling cURL timeout
[API:debug: 22:26:55] Set cURL timeout[2] to 106449 ms from 11997
```

Again, I want to reiterate that everything works just fine on first boot.

**Comment by polmr** [comment]
Hi @kwatson , I am afraid file system notifications are not forwarded via samba. Changes done by the machine that mounts the cifs filesystem will be notified, changes done in the origin won't. `reload` will reload your account entirely: forcing a re-scan, but that will entail reloading your account.
You can use alternatives to syncing: (simply uploading a folder with `put` in a cron job, or using `backup` command)

**Comment by kwatson** [comment]
Hi @polmr -- thanks for the response. I was afraid of that...

The data on the mounted smb share does not change that frequently, so I just remind myself to run `mega-sync` and then `mega-quit`, however it would be nice to to pass a flag to `mega-sync` that would kill the `mega-cmd-server` after the initial sync is done (e.g. when the `mega-sync` state is `Synced`). That would allow me to use a cronjob to trigger that daily. 

With respect to `put` and `backup`:

1. Will `put` use the same _engine_ as `sync` to push data to Mega? I don't want to duplicate data on Mega, or re-upload data that's already uploaded.
2. Initially i tried to use `backup`, however it appeared that it would upload a full copy of the data again on each backup. It took about 1.5 weeks to perform the initial sync, so that is not really feasible to re-upload all the data on each backup run.

**Comment by polmr** [comment]
`1. Will put use the same engine as sync to push data to Mega? I don't want to duplicate data on Mega, or re-upload data that's already uploaded.`
No, it doesn't use the same engine. It will create version on existing files, but won't remove files that no longer exist locally. It will only upload files when they have changed.
2. one minor note regarding `backup`. It will not reupload files when they haven't change: it will just issue remote copies.

**Comment by kwatson** [comment]
Thanks for the response. I think I will continue using `mega-sync`, even with the manual work, i think it fits my workflow best.
