### ISSUE TITLE
"userattr" command crashes the shell in Windows

### ISSUE THREAD

**Issue by steve4444** [meganz/MEGAcmd#4]
Just run:

    userattr
It freezes. Ctrl-c then kills the shell instead of exiting the command.

**Comment by steve4444** [comment]
MEGA CMD version: 0.9.5: code 90500

Windows popup after "userattr"
-------------------------------

    MEGAcmd has stopped working 
    A problem has caused the program to stop working ......



MEGAcmdShell session after "userattr"
------------------------------------

    userattr   
    ERROR reading output code: ERROR reading output (state change): The sever problably exited.109
                          
    Server not running. Initiating in the background...



megacmdserver.log
-----------------

When running MEGAcmdShell.exe:
                                                                
    [API:info: 21:22:02] Request (APP_VERSION) starting
    [API:debug: 21:22:02] DNS cache hit for g.api.mega.co.nz (IPv4)
    [API:debug: 21:22:02] POST target URL: https://g.api.mega.co.nz/cs?id=*****&sid=*****
    [API:debug: 21:22:02] Sending: [{"a":"lv","a":"******"}]
    [API:debug: 21:22:02] Using the IP of the hostname
    [API:debug: 21:22:02] Setting cURL timeout to 1 ms
    [API:debug: 21:22:02] Disabling cURL timeout
    [API:debug: 21:22:02] Adding/setting curl socket 772
    [API:debug: 21:22:02] Setting cURL timeout to 1 ms
    [API:debug: 21:22:02] Disabling cURL timeout
    [API:debug: 21:22:02] Setting cURL timeout to 11891 ms
    [API:debug: 21:22:02] Removing socket 772
    [API:debug: 21:22:02] CURLMSG_DONE with HTTP status: 200
    [API:debug: 21:22:02] Received: [-2]
    [API:debug: 21:22:02] Setting cURL timeout to -1 ms
    [API:warn: 21:22:02] Request (APP_VERSION) finished with error: Invalid argument
    [debug: 21:22:02] Couldn't get latests available version: Invalid argument
    [debug: 21:22:02] Client arrived first when connecting to namedPipe to inform state. 0000032C

When issuing "userattr":       

    [API:info: 21:23:02] Request (GET_ATTR_USER) starting
    [API:err: 21:23:02] Getting invalid scope
    [API:err: 21:23:02] Error starting request: -2
    [API:warn: 21:23:02] Request (GET_ATTR_USER) finished with error: Invalid argument
    [err: 21:23:02] Failed to get user attribute avatar: Invalid argument
    [API:info: 21:23:02] Request (GET_ATTR_USER) starting
    [API:info: 21:23:02] Request (GET_ATTR_USER) finished
    [API:info: 21:23:02] Request (GET_ATTR_USER) starting
    [API:info: 21:23:02] Request (GET_ATTR_USER) finished
    [API:info: 21:23:02] Request (GET_ATTR_USER) starting
    [API:debug: 21:23:02] DNS cache hit for g.api.mega.co.nz (IPv4)
    [API:debug: 21:23:02] POST target URL: https://g.api.mega.co.nz/cs?id=*****&sid=*****
    [API:debug: 21:23:02] Sending: [{"a":"uga","u":"*****","ua":"*!authring","v":1}]
    [API:debug: 21:23:02] Using the IP of the hostname
    [API:debug: 21:23:02] Setting cURL timeout to 1 ms
    [API:debug: 21:23:02] Disabling cURL timeout
    [API:debug: 21:23:02] Adding/setting curl socket 772
    [API:debug: 21:23:02] Setting cURL timeout to 0 ms
    [API:debug: 21:23:02] Disabling cURL timeout
    [API:debug: 21:23:02] Setting cURL timeout to 11984 ms
    [API:debug: 21:23:02] Removing socket 772
    [API:debug: 21:23:02] CURLMSG_DONE with HTTP status: 200
    [API:debug: 21:23:02] Received: [{"av":"********8","v":"***********"}]
    [API:debug: 21:23:02] Setting cURL timeout to -1 ms
    [API:info: 21:23:02] Request (GET_ATTR_USER) finished
    [API:debug: 21:23:02] Saving SCSN ***** with 0 modified nodes, 1 users, 0 pcrs and 0 chats to local cache (1)
    [debug: 21:23:02]  1 user received or updated

**Comment by polmr** [comment]
Reproduced! This fixes it: https://github.com/meganz/MEGAcmd/commit/a229ba3e27f9b153dd824a987548af4bd2ece9eb . It'll be included in the next release. Thanks for reporting @steve4444 !

**Comment by steve4444** [comment]
Thanks, any schedule for next release?

**Comment by polmr** [comment]
Not yet decided. Hopefully soon (probably within the next month)

**Comment by steve4444** [comment]
cool
