### ISSUE TITLE
MEGAcmd installation

### ISSUE THREAD

**Issue by Chirwa79** [meganz/MEGAcmd#423]
![20200730_000407](https://user-images.githubusercontent.com/68973508/88859723-97618000-d1fa-11ea-8cf1-26b993fd235f.jpg)

How do i install MEGAcmd. Previously i used to run the istallation software with no problem and now the application is stuck on command mode

**Comment by aabellagm** [comment]
Hi,

Do you need MEGAcmd or MEGAsync?
megacmd is a command line tool. The GUI one is MEGASync. You can found it here in case you need MEGASync: https://mega.nz/sync

In case you need the command line tool, here you have a user guide that could help you: [User Guide](https://github.com/meganz/MEGAcmd/blob/master/UserGuide.md)

**Comment by Chirwa79** [comment]
Thanks
