### ISSUE TITLE
Issues related to length of URI in webdav

### ISSUE THREAD

**Issue by kadogo** [meganz/MEGAcmd#450]
Hello,

I remarked that in some case if I have too long directories webdav not work (no response from browser or curl).
I guess it's because sometimes my URL is too long, if I make it short it work correctly.

I'm curious to know if there is a way to solve that issue other than sorting all my directories?

Thanks for your answer.

**Comment by polmr** [comment]
Hi @kadogo , 
As far as I know there should be no limitation in length to paths. You wouldn't happen to have any example? I am unable to reproduce this

**Comment by kadogo** [comment]
Hello @polmr 

I must say that I tried to reproduce it and it couldn't work maybe I was not completely updated. I don't know.
You may close this issue I will open it again if I find the issue and add an example to try to reproduce it.

**Comment by polmr** [comment]
ok, thanks for reporting that anyway ;-)
