### ISSUE TITLE
Missing megacmd 1.4 *.deb builds for Raspbian

### ISSUE THREAD

**Issue by morozov** [meganz/MEGAcmd#455]
Filing this for visibility. Currently, the latest [available](https://mega.nz/linux/MEGAsync/Raspbian_10.0/armhf/) version is 1.2.0. The builds may be blocked by https://github.com/meganz/MEGAcmd/issues/451.

**Comment by polmr** [comment]
@morozov  thanks for opening both issues, we will soon build new versions taking the #451 into account.

**Comment by morozov** [comment]
Closing as Rasbian builds of version 1.5.1 have been published.
