### ISSUE TITLE
MEGAcmd webdav URL

### ISSUE THREAD

**Issue by AllanVan** [meganz/MEGAcmd#474]
I'm having issues when accessing the URL provided by MEGAcmd's webdav command, 
webdav / 

it generates the URL
http://127.0.0.1:4443/XXXXXX/Cloud%20Drive

I use a third-party program to deal with the Webdav provided, but even in Windows I can't mount it (network drive, inaccessible, Win7 64 bits) The issue is with the %20 character (whitespace). The URL works fine in the web browser (chrome).

Is there any way around this? Maybe a way to access the root path with an alternative name, like 
http://127.0.0.1:4443/XXXXXX/root
?
I tried several ways, including encasing the URL in quotes, but the issue is the non-UTF8 character. The only workaround I've found is to make another main folder in root, and put all folders inside that folder, then start webdav there

webdav /main
which results in
http://127.0.0.1:4443/YYYYY/main

Any alternatives to this?

**Comment by AllanVan** [comment]
I was mistaken, so I'm closing this.

**Comment by tanscha21** [comment]
can u please tell me how u created that link?
webdav /path/mega/folder just gives me "path not found" :(
would be amazing!
