### ISSUE TITLE
Date and time of backup incorrect

### ISSUE THREAD

**Issue by Prog72** [meganz/MEGAcmd#481]
I see there are already issues regarding this but I have been specifically requested by MEGA Support to open a new issue.

The dates and times of my backups are approximately 41 years in the past. For example a backup at 1650 today (02 Jan 2021) has a date of 05 Mar 1980 at 14:54. This also needs to be taken in to account when creating backups ie if I want a backup to occur every day at 04:00 then I need to set it for 02:04.

I am running version 1.2.0.6 on Raspbian Buster on a Raspberry Pi 4.

**Comment by diogosena** [comment]
I have the same problem... did you discover anything? @Prog72

**Comment by Prog72** [comment]
> I have the same problem... did you discover anything? @Prog72

No, nothing at all. I've just been ignored by the developers.

**Comment by Prog72** [comment]
Fixed in the latest release. Many thanks to the developers.
