### ISSUE TITLE
Default file permission for new files and folder

### ISSUE THREAD

**Issue by saurabh-kushwah** [meganz/MEGAcmd#486]
I have a folder location which is shared using samba and it is the location where i sync mega files and folder. It has some default file permissions which are set so that is can be accessible in network. But the file downloaded from mega always have read write access to the user(-rx----) but does not set the default file permission (-rxrxr-) as a result i have  to manually change the file permission.

Due to the default permission the files downloaded cannot be shared across network.

OS: Ubuntu Server

**Comment by 3ncod3** [comment]
Same problem here, any updates on this?
