### ISSUE TITLE
API debug telling "Not enough available space" when my localstorage and cloud storage are not full

### ISSUE THREAD

**Issue by kadogo** [meganz/MEGAcmd#494]
Hello

I'm using megacmd for exposing a webdav server. I remark that if I expose the webdav server and mount it using rclone (I didn't tried with another application but if you know one on Debian to mount a webdav service I would be happy to test).

I just do a `du -sh ./webav-mount/` and I find the latest snippet in megacmd log. And my command never end. I had the same isse on 3 PC (nas, laptop and desktop) so the localstorage that would be full not seem possible and I didn't find any info about the message here so I guess it's a message from Mega API.

```
[API:debug: 03:05:07] Not enough available space
[API:debug: 03:07:36] Received -4095 bytes
[API:debug: 03:07:36] Finishing request. Connection reset by peer or unsupported data
[API:debug: 03:07:36] Connection closed: 0 port = 4443 closing async handle
[API:debug: 03:07:36] Connection deleted, port = 4443
```

Thanks for your help, cheers.

**Comment by cristianlivella** [comment]
I'm having the same problem, I can't figure out what's wrong.

**Comment by kadogo** [comment]
In case it can help, I use a paid account so I not really know what happen.
If a dev could take a look to maybe give us an idea about what mean this message?

**Comment by sergiohs84** [comment]
Hi @kadogo 

Thanks for reporting the issue. The `Not enough available space` message is not related to your local neither remote storage capacity. It's about the size of a buffer used by the WebDAV server, indeed, which apparently doesn't have enough space to allocate the HTTP header that requires to be sent by the internal HTTP server that supports WebDAV.

Would you mind to share a log with us?

**Comment by kadogo** [comment]
Hello @sergiohs84 

Sure is there a particular log / debug level needed ? Or maybe some operations that I can test so I can send all the logs here.

**Comment by polmr** [comment]
For further referrals to this issue https://github.com/meganz/MEGAcmd/issues/507
