### ISSUE TITLE
"users" command does not show all users  I am in contact relationship with

### ISSUE THREAD

**Issue by steve4444** [meganz/MEGAcmd#5]
Output from 

    users

is just a subset of the users listed as contacts in the web interface

**Comment by polmr** [comment]
This should not happen. All users listed as contacts in the web should appear as contacts in MEGAcmd. It might be a connectivity issue (some data is out-dated). If that is the case, restarting MEGAcmd should fix it. If the issue persist, please contact us, or better off: provide us with logs as indicated in #2.
