### ISSUE TITLE
Using megasync to sync with joplin

### ISSUE THREAD

**Issue by antonvons** [meganz/MEGAcmd#527]
Hello, I use joplin notes and used to sync with Dropbox. Now that I have swapped over to mega.nz I’m wondering how I can sync now. Joplin just says to enter a webDAV URL. My question is can I do this and if so how?  Thanks, Anton

**Comment by antonvons** [comment]
I should also mention that I will need to Sync Joplin Notes on a Windows 10 PC, iPad and iPhone

**Comment by smonsec** [comment]
Any updates to adding megasync as an option?
