### ISSUE TITLE
Access shared folders in the mega shell

### ISSUE THREAD

**Issue by DroidFreak32** [meganz/MEGAcmd#53]
As the title says, is there any way I can access ( ```cd```  into )shared folders from the mega-cmd shell?

**Comment by polmr** [comment]
Use `mount` to list the list of INSHARES. It will output something like:
```
INSHARE on contact@domain:name_of_folder (full access)
```
you can cd to it with:
```
cd contact@domain:name_of_folder
```

**Comment by phoenix1887** [comment]
OH MY GOD I SPENT 2 HOUR LOOKING FOR THIS AND TRYING TO FIGURE IT OUT! THANKS FOR POSTING @polmr and @DroidFreak32 

SOMEONE ON THE MEGA TEAM NEEDS TO ADD THIS TO THE DOCUMENTATION ALL OVER THE PLACE, THERE IS LITERALLY NO MENTION ANYWHERE ABOUT INTERACTION WITH SHARED FOLDERS... UNLESS YOU HAPPEN TO RANDOMLY TRY MEGA-MOUNT COMMAND TO VIEW "NODES" WHICH DON'T APPARENTLY OFFER MUCH IN TERMS OF A DESCRIPTION.

Even the command mega-mount --help gives you this:

"Lists all the main nodes"

K..... what does that mean to a random human? There needs to be lots of mentions and references to dealing with shared folders throughout the documentation and examples with shared folders. It's almost like the devs forgot that shared folders even exist when they wrote the docs.

Thanks TEAM! Love Mega!

**Comment by polmr** [comment]
Thanks @phoenix1887 , we are improving that docs

**Comment by Himusaki** [comment]
@polmr 

can u tell me exactly how can i mount inshare to my desktop?

**Comment by Himusaki** [comment]
plz see my screenshot @polmr 
![image](https://user-images.githubusercontent.com/83940470/172035233-66da8e08-6bee-40ec-b1b3-a1f0ec72774f.png)

**Comment by Himusaki** [comment]
it says path not found @polmr

**Comment by gsdefender** [comment]
If the shared folder has spaces, you must use double quotes to use the path.
