### ISSUE TITLE
Reason behind code 250 for the FTP

### ISSUE THREAD

**Issue by kadogo** [meganz/MEGAcmd#543]
Hello, copy paste of my question through mail.

---

Related to https://github.com/meganz/MEGAcmd/issues/507 I tried the FTP
serving and used rclone to copy my files in the FTP. But it looks like
that rclone and his FTP library were seeing the "250" code as an error.

After making them few modifications
https://forum.rclone.org/t/transfer-on-mega-in-ftp-mode-is-not-working/24642
we could make it work but they (and me) where curious why the code "250"
if there is a reason behind it.

Thanks for reading me and have a nice day.

---

There is still an open question on https://github.com/meganz/MEGAcmd/issues/507 about using FTP instead of webdav. Thanks for your future answers.

**Comment by aabellagm** [comment]
Hi Kadogo,

The code "250." appears in the [RFC 959](https://datatracker.ietf.org/doc/html/rfc959). It appears in "5.4.  SEQUENCING OF COMMANDS AND REPLIES" as a valid reponse to a STOR command.

Not sure why it is interpreted as an error, but we think it shouldn't. We are open to consider changing the code if there is a reason to, but we think 250 code is ok.

I've tested it with ftp CLI tool in Linux with no problem:
```
ftp> cd tmp
250 Directory successfully changed
ftp> put example.pdf 
local: example.pdf remote: example.pdf
227 Entering Passive Mode (127,0,0,1,5,224)
150 Opening data connection for storing example.pdf
250 Requested file action okay, completed.
381337 bytes sent in 0.01 secs (38.8621 MB/s)
ftp> delete example.pdf
250 Requested file action okay, completed.
```

Thanks!

**Comment by kadogo** [comment]
Hello @aabellagm 

Thanks for your answer.

No issue if it's a valid response in the RFC.
I will forward the issue to rclone so that the change is backed with a reason ^^

Have a good day.
