### ISSUE TITLE
megacmd sync for synology - is there any progress bar or similar for terminal

### ISSUE THREAD

**Issue by konju1** [meganz/MEGAcmd#566]
megacmd sync for synology work pretty well, but i can't see anywhere progress.
on mac terminal there is only message "resuming session" and it's syncing but i don't know when is finished or what is going on.

**Comment by LmaoImo** [comment]
Hi konju1, 
May I ask how did you sync your mega folder with Synology using megacmd? 

I've installed the MEGAcmd on Synology, and connected to my Synology NAS through Windows Powershell SSH.

I've also successfully login to my mega account, but I guess I didn't type my folder path right.

Assuming I would like to sync a folder under my Synology NAS at "\DS920plus\test\test" with a folder on mega named "megatest", how should I write it?

I tried the below:
mega-sync \DS920plus\test\test /megatest
mega-sync \192.168.0.xxx\test\test /megatest
mega-sync /test/test /megatest

I kept getting the error message of "failed to sync folder: not found" no matter how I change the input.

Any help would be much appreciated, thanks!
