### ISSUE TITLE
UI is huge

### ISSUE THREAD

**Issue by grafa** [meganz/MEGAcmd#59]
I use Debian 9.0 build, screen is 1440p.

The result:

![image](https://user-images.githubusercontent.com/198654/41528586-c8a9085c-72ea-11e8-8d6f-21bf0411f20c.png)

**Comment by polmr** [comment]
Please, this issue should be posted in MEGAsync repository: https://github.com/meganz/MEGAsync/issues

**Comment by polmr** [comment]
in any case, you can play with QT_SCALE_FACTOR. Close MEGASync and try to launch it this way:
```
QT_SCALE_FACTOR=1 megasync
```

**Comment by grafa** [comment]
Damn, sorry :)

Your solutions works. I will use that as workaround for now. Feel free to move the issue to whereever you need.
