### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by jignac05** [meganz/MEGAcmd#608]
I posted [this issue on MEGAsync GitHub](https://github.com/meganz/MEGAsync/issues/649) and I was asked in mail to post it here. So I am posting it here.

**Comment by jignac05** [comment]
Any help?

**Comment by pichinep** [comment]
Did you solve this? i have the same issue and found no info on the web...

Thx

**Comment by jignac05** [comment]
No, I just only send error log files to mega support, but they haven't gave me solution yet.

**Comment by pichinep** [comment]
Try with:
sudo apt remove qt5dxcb-plugin

i've used it and it worked... good luck

**Comment by jignac05** [comment]
Thank you!

Finally something that worked!

**Comment by pichinep** [comment]
You welcome... Glad it worked for you too...! :-D

**Comment by dalekirkwood** [comment]
Thanks! This worked. I was getting stressed 😁
