### ISSUE TITLE
empty directory with 7.5 GB of data in it?

### ISSUE THREAD

**Issue by systemdlete** [meganz/MEGAcmd#610]
I am totally confused by what I am seeing when I use your web gui.   On my local machine, I have mapped several local directories to my cloud top-level directories and subdirectories. When I use the mega-cmd tool, I can see my cloud files listed, and they match the local ones.

But I have, for instance, a top-level directory in my account which I call megacloud.  In the GUI, it says its size is 7.5GB, but when I click on it to open it, it claims "empty directory." This is slightly frightening.   I'm not sure which one is correct or incorrect.  I just hope, either way, I am not missing any data!

I am also seeing errors in a log file (attached) under my .megaCmd subdirectory in $HOME.  I've been seeing console (terminal output) errors also, on and off throughout the day today, similar to these.

Please help me to understand this problem further.   Thank you for your prompt reply as I find this upsetting.

**Comment by keliew** [comment]
Am wondering if this is related to https://github.com/meganz/MEGAcmd/issues/587?

**Comment by systemdlete** [comment]
keliew:  No idea.  Determining that would probably require some deep knowledge and understanding of the code, which I do not have access to and/or will not be spending my time investigating.  The last time I had any issues with Mega was years ago, and I figured all had been sorted out since then as I have not experienced any problems since.   It is the main reason I decided to purchase a paid account.   Please see to it that this is addressed immediately.    Maybe Mega can temporarily restore the old webui software which worked!

**Comment by systemdlete** [comment]
Heh heh heh.   

I restarted firefox (78.15) and--viola!--all files and subdirectories display correctly again.   (I'll be upgrade to a much more recent firefox shortly...)

I should have realized it might be the browser.   As I mentioned in my previous post to this thread, I've not had any problem(s) with mega for years and years.  I figured this out by using an old "trick:"  I tried viewing my account in a different browser (chromium) and that worked fine.   That clued me in on the idea of restarting the firefox browser.

Headslap. Please close this issue...
