### ISSUE TITLE
Automatically sync at NAS Synology

### ISSUE THREAD

**Issue by MartinSLK** [meganz/MEGAcmd#634]
Hello,

I need help, how to add a script to automatically sync for NAS Synology. I did all things from this tutorial https://github.com/meganz/MEGAcmd/blob/master/UserGuide.md but after every restart I must via cmd start new synchronization.

Can you help me, how to do it an script for aztomatically sync after start NAS Synology?

Many thanks,
Martin

**Comment by angelds-mega** [comment]
Hello Martin, sync paths will be automatically disabled if the paths are inaccessible by the time MEGAcmd server starts.

Could you please confirm if they are mounted?

Also please double-check if the user running MEGAcmd has permissions to access those paths.

Thank you.

**Comment by MartinSLK** [comment]
Hi,
I have set up MEGAcmd, and their folders. I just can't seem to set it to
sync automatically after boot. I'm posting below the details of the script,
but unfortunately it doesn't work for me. Why?

po 14. 3. 2022 o 23:31 Angel Santos ***@***.***> napísal(a):

**Comment by JuanuSt** [comment]
Check this: https://github.com/meganz/MEGAcmd/issues/588#issuecomment-1046953573

**Comment by JuanuSt** [comment]
Probability you will have to adapt the script to your environment.

For execute the script after boot, you have to add a cronjob:
crontab -e

@reboot ~/scripts/start_megaCMD_syncs.sh

**Comment by MartinSLK** [comment]
Can you write me what script should I put in the NAS to make it work after
boot/reboot?
Thanks :)

št 17. 3. 2022 o 10:54 Juanu ***@***.***> napísal(a):

**Comment by MartinSLK** [comment]
Hello again,
because I not received a reply, I try ask again.

Please, can you write me how the resulting code that I will write to the
NASko task scheduler will look like? So far nothing works for me, neither
adding part of your code, nor anything so far...
I've tried this, for example, but it didn't help. Even the code from the
comment above didn't help... What then?

BTW, the application on the NAS will be when !!!??? Are we users who still
paid for a subscription service really supposed to play programmers?
Instead of letting the programmers who have (MEGA programmers) do it?

I am really frustrated about this!! You are delivering a service that is
INCOMPLETE. Thank you for your help and I believe the priority to complete
and fix the applications on Synology and QNAP NAS are TOP priority.... As
long as you have an app for minor services like Linux....

This not work for me :

Poslali ste
#!/bin/bash
export HOME=/var/services/homes/admin
export USER=admin
cd $HOME
/var/packages/MEGAcmd/target/mega-cmd-server
exit --only-shell

Also not work for me
https://github.com/meganz/MEGAcmd/issues/588#issuecomment-1046953573

Any options how to will works? ...


št 17. 3. 2022 o 12:37 Martin Klokner ***@***.***> napísal(a):

**Comment by MartinSLK** [comment]
Hello, any reply please?

**Comment by polmr** [comment]
Hi, @MartinSLK , I think, these lines from https://github.com/meganz/MEGAcmd/blob/master/UserGuide.md#nas-support may be of assistance to you:

### NAS Support
We have released packages for QNAP and Synology, which you can download and install from the App Center in QNAP, and the Package Center in Synology.   In QNAP, please make sure to turn on "Enable home folder for all users" from the control panel, and set HOME=/share/homes/<username> before starting any MEGA commands, and in Synology, 'Enable user home service', so that the `mega-cmd-server` creates the `.megaCmd` local cache folder there (as the default HOME location may be erased on restart).

**Comment by dwmega** [comment]
Hey there, @MartinSLK.

How are you trying to use the solution:
`#!/bin/bash`
`export HOME=/var/services/homes/admin`
`export USER=admin`
`cd $HOME`
`/var/packages/MEGAcmd/target/mega-cmd-server`

I imagine you found that snippet on Reddit :)

That "script" is intended to be used from Synology's task scheduler.

The variable `USER` should be changed to your user's username. For me, for instance, it would be `dw`. It'll the same account you use to SSH into the device.

**Comment by MartinSLK** [comment]
Hello,
your script didn't help me and it didn't work.
It was hours of trying and testing (!!!) that should have been done by the
MEGA programmers (not me), but for the rest of you, if MEGA doesn't work
for you after startup like it did for me, just paste this code. Nothing
more.

#!/bin/bash
> cd /var/packages/MEGAcmd/target/
> mega-cmd-server


Martin

št 24. 3. 2022 o 20:20 David Ward ***@***.***> napísal(a):

**Comment by MartinSLK** [comment]
#!/bin/bash
cd /var/packages/MEGAcmd/target/
mega-cmd-server

**Comment by MartinSLK** [comment]
- [ ] #!/bin/bash
- [ ] cd /var/packages/MEGAcmd/target/
- [ ] mega-cmd-server

**Comment by MartinSLK** [comment]
```
#!/bin/bash
cd /var/packages/MEGAcmd/target/
mega-cmd-server
```

**Comment by MartinSLK** [comment]
Hello,
your script didn't help me and it didn't work.
It was hours of trying and testing (!!!) that should have been done by the
MEGA programmers (not me), but for the rest of you, if MEGA doesn't work
for you after startup like it did for me, just paste this code. Nothing
more.

```
#!/bin/bash
 cd /var/packages/MEGAcmd/target/
 mega-cmd-server
```

Martin
