### ISSUE TITLE
thumb-nailing 

### ISSUE THREAD

**Issue by srulikuk** [meganz/MEGAcmd#64]
I have a about 300,000 files in mega-sync, all the files are encrypted locally before they hit the local mega dir
The problem is that each time mega starts or even when a new batch of files hit the dir, mega consumes almost 90% of CPU trying to create thumbnails/processes the metadata of the files.
I have the syncs on 3 different servers and this is slowing everything down, it can take up to 45 minute for mega to finish trying to create a thumbnail for all the files.

Please can you make an option to turn off those features its just not possible to continue using it like this.

Thanks

**Comment by polmr** [comment]
An option to disable the processing of images will be available in the next release.

**Comment by srulikuk** [comment]
@polmr 
Many thanks, same for other file types pdf/tiff/mp3/vid files etc (if they are also processed)?
any eta for next release? 
when released please advise here and instruction how to turn it off.
once again many thanks

**Comment by srulikuk** [comment]
@polmr 
has the option to disable yet been added?

**Comment by polmr** [comment]
It's been implemented here and included in the `develop` branch as a new the command (`graphics`): https://github.com/meganz/MEGAcmd/commit/cfb1a8a36339a1d4bab11bcb34676a43c540c236 
Will be included in the next release (hopefully next week or the following)

**Comment by srulikuk** [comment]
@polmr 
Has it been released yet? if yes how do I disable media file processing?

**Comment by polmr** [comment]
Not yet, but it's about to be release in the next days.

**Comment by polmr** [comment]
Done in the new release 1.0.0. `graphics off` will disable graphics processing. Extra info: `graphics --help`

**Comment by srulikuk** [comment]
> Done in the new release 1.0.0. `graphics off` will disable graphics processing. Extra info: `graphics --help`

Just wondering if this feature will be available on megasync client on linux?
