### ISSUE TITLE
FTP to cloudrive

### ISSUE THREAD

**Issue by zelgard** [meganz/MEGAcmd#659]
How to setup ftp for cloud drive instead of ftp of a folder in cloud drive?

**Comment by voc-mega** [comment]
Hello!
We implemented a local proxy that talks FTP/FTPS to the client software and the MEGA protocol to the MEGA servers through MEGA CMD https://mega.nz/megacmd
You can find a brief tutorial here:
https://github.com/meganz/MEGAcmd/blob/master/contrib/docs/FTP.md
Please let us know if you need further assistance.
