### ISSUE TITLE
mega-login not working as advertised / users guide = advances users guide, where is getting started?

### ISSUE THREAD

**Issue by dkuchay** [meganz/MEGAcmd#662]
Mega-login does not work as advertised. Where is the getting started or quick start? My password has an exclamation point in it and that is the point of breaking "event not found". Even with quotes "i" get unexpected returns from mega-login. Arch linux current at date of posting. Please update basic functionality to the guide and add special characters to login strings. OR example some basic login strings in the guide. It starts off with advanced scripting. Can't get around errors on login. I can login via web browser and via app on phone with no issues.

**Comment by dkuchay** [comment]
Close this issue. I was only able to get this to work by reading other users perils and help tickets. Not by reading your docs. The docs need updating to show basic login functionality. Only by issuing "mega-cmd" followed by login "user@example.com" was I able to login.

**Comment by polmr** [comment]
Hi @dkuchay 

Exclamation mark is something that your client shell (presumably bash) is interpreting, it's not that MEGA CMD is missinterpreting it (it didn't even reach MEGA CMD client).

e.g:
```
echo "something!happening"
```
would report a similar error

You can always escape that by using single quotes:
```
echo 'echo 'something!happening'
```

**Comment by dkuchay** [comment]
Thanksfor your reply. Please close this as I am able to use interactive mode now.
