### ISSUE TITLE
[API:err: 06:18:52] Invalid value for node attr fav: 0

### ISSUE THREAD

**Issue by DanyGee** [meganz/MEGAcmd#680]
Hi,

getting following error when trying to initiate mega-cmd-server:

**[API:err: 06:18:52] Invalid value for node attr fav: 0**

MEGAcmd version: 1.5.1.1: code 1050101 

Syncs state:

ACTIVE   STATUS   ERROR
Disabled Inactive NO   
Disabled Inactive NO   
Disabled Inactive NO   
Disabled Inactive NO   
Disabled Inactive NO   

OS:
System:    Kernel: 5.13.0-51-generic x86_64 bits: 64 compiler: N/A Desktop: Gnome 3.38.4 Distro: Zorin OS 16.1 
           base: Ubuntu 20.04 LTS Focal 
Machine:   Type: Desktop System: LENOVO product: C460 v: Lenovo Product serial: <filter> 
           Mobo: LENOVO model: SHARKBAY v: 31900006 STD serial: <filter> UEFI: LENOVO v: IMKT23AUS date: 05/18/2016 
CPU:       Topology: Dual Core model: Intel Core i3-4130T bits: 64 type: MT MCP arch: Haswell rev: 3 L2 cache: 3072 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 23145 
           Speed: 1131 MHz min/max: 800/2900 MHz Core speeds (MHz): 1: 980 2: 1521 3: 1025 4: 903 
Graphics:  Device-1: Intel 4th Generation Core Processor Family Integrated Graphics vendor: Lenovo driver: i915 v: kernel 
           bus ID: 00:02.0 
           Device-2: NVIDIA GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] vendor: Lenovo driver: nouveau 
           v: kernel bus ID: 01:00.0 
           Display: x11 server: X.Org 1.20.13 driver: nouveau resolution: 1920x1080~61Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 4400 (HSW GT2) v: 4.5 Mesa 21.2.6 direct render: Yes 
Audio:     Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio driver: snd_hda_intel v: kernel bus ID: 00:03.0 
           Device-2: Intel 8 Series/C220 Series High Definition Audio vendor: Lenovo driver: snd_hda_intel v: kernel 
           bus ID: 00:1b.0 
           Sound Server: ALSA v: k5.13.0-51-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Lenovo driver: r8169 v: kernel port: d000 
           bus ID: 05:00.0 
           IF: enp5s0 state: down mac: <filter> 
           Device-2: Realtek RTL8188EE Wireless Network Adapter vendor: Lenovo driver: rtl8188ee v: kernel port: c000 
           bus ID: 06:00.0 
           IF: wlp6s0 state: up mac: <filter> 
Drives:    Local Storage: total: 111.79 GiB used: 68.91 GiB (61.6%) 
           ID-1: /dev/sda vendor: Kingston model: SA400S37120G size: 111.79 GiB 
Partition: ID-1: / size: 109.04 GiB used: 68.91 GiB (63.2%) fs: ext4 dev: /dev/sda2 
Sensors:   System Temperatures: cpu: 29.8 C mobo: 27.8 C 
           Fan Speeds (RPM): N/A 
Info:      Processes: 270 Uptime: 21m Memory: 7.68 GiB used: 2.70 GiB (35.1%) Init: systemd runlevel: 5 Compilers: gcc: 9.4.0 
           Shell: bash v: 5.0.17 inxi: 3.0.38 

Please help, need the sync to WORK!

**Comment by polmr** [comment]
The error shown is not a fatal failure, and not related to the syncs. Your syncs are disabled. Unfortunately, the reason for that was not saved when that happened.

You would need to manually re-enable them. 
`mega-sync` would list their Id's.

and then:

```mega-sync -r 'ID'```
 will enable the sync you want.

use `mega-sync` again to ensure they are operative, if there's a permanent reason for them to be disabled, it would probably be shown now
