### ISSUE TITLE
Can't login on my QNAP NAS

### ISSUE THREAD

**Issue by philippetev** [meganz/MEGAcmd#683]
Hi!
I've installed Megacmd 1.50 through the Entware repository on my QNAP NAS (aarch64, Linux 4.2.8). Every time I try to login, I get this:

```
[Initiating MEGAcmd server in background. Log: /opt/root/.megaCmd/megacmdserver.log]
MEGA CMD> login ******.*****@*****.com
Password:
[API:info: 04:53:30] Fetching nodes ...
[API:err: 04:53:31] Failed to fetch nodes: Bad session ID
MEGA CMD>
```

I was able to compile the latest version 1.51(along with the latest SDK/libmega, targeting that version) and I get the same message with it.
There is version 1.4 in the QNAP Store that doesn't seems to have such problem.

If any other info is needed, I'll provide.

**Comment by mattw-mega** [comment]
Hi, if you build against tag/v3.9.11e, that should be fixed for QNAP.  thanks

**Comment by philippetev** [comment]
That solved the problem. Thanks!
