### ISSUE TITLE
Starting the MegaCmd server from a script

### ISSUE THREAD

**Issue by steve4444** [meganz/MEGAcmd#7]
Is it possible to start the server from a script?    
Using: 

    & "$env:LOCALAPPDATA\MEGAcmd\MEGAcmd.exe"

halts execution, so it needs to be used from a separate session.

I would like to run the server from a script, check if the command returns successfully and possibly execute the script commands.     
Is there any command option to fork `MEGAcmd.exe` in the background after a successful execution?

Side note:    
IMHO naming conventions are a bit misleading for the first time users.    

1. The `MEGAcmd.lnk` actually links to `MEGAcmdShell.exe` and not `MEGAcmd.exe`.    
2. There is no `MEGAcmdServer.lnk` and this is necessary to run batch scripts. 
3. `MEGAcmd.exe` starts a server and that is not what the name naturally implies.

I spent some trial-and-error time to catch this. I warmly suggest suggest that in the next release you at least:    
Rename `MEGAcmd.exe` as `MEGAcmdServer.exe` or the likes.

**Comment by polmr** [comment]
You might want to try https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-5.1  with -redirectstandardoutput and -nonewwindow

Regarding the naming conventions ... I have to agree with you. We'll take your comments into consideration and try to reduce the confusion. Thanks for the inputs
