### ISSUE TITLE
login with credential file

### ISSUE THREAD

**Issue by sakitA** [meganz/MEGAcmd#70]
Hello. I want to create a config file under my home directory with my MEGA account info so when I or my shell try to login mega-login read my credentials from this config file instead of typing email and password. Is there any way to do this current with MEGAcmd tools?

**Comment by polmr** [comment]
No, there isn't, but you can create a config file with this contents
```
user=YourUser@Na.me
password=YourPassword
```
And automate the login with something like this:
```
mega-login `grep user /path/to/conf/file | awk -F "=" '{print $NF}'` `grep password /path/to/conf/file | awk -F "=" '{print $NF}'`
```

**Comment by sakitA** [comment]
I understood. Thank you very much
