### ISSUE TITLE
Phylogenetic tree at numerical dataset?

### ISSUE THREAD

**Issue by sekhwal** [meganz/MEGAcmd#717]
How to make phylogenetic tree using following type of dataset. I have 71 samples and 3003 row in the input file. Please suggest any way to get the tree on these type of data.

example file:
4 11
Sample1 11 - - - - 89 678 9 2 3 55
Sample2 11 8 7 6 5 - - 78 765 9 -
Sample3 12 - - - - 45 786 - - -
Sample4 23 8 8 7 - - - 6 5 5-

**Comment by polmr** [comment]
Wrong repostiroy. Already posted in the right one: https://github.com/ropensci/phylogram/issues/3
