### ISSUE TITLE
mega put - didn't update existing file on remote repository

### ISSUE THREAD

**Issue by bovirus** [meganz/MEGAcmd#72]
@polmr 

Hello.

I tried to use the command

put localfilename remotepath/remotefilename

but it didn't works.
The file is not updated (new file date/time)

If ir remove the file then use the same command (put) it works.

Is it available a command option to overwrite an existing file in remote repository?
If is not available please could add this command option?

**Comment by bovirus** [comment]
@polmr 

No news.
It's important pout command can update an existing remote file.

**Comment by polmr** [comment]
Hi @bovirus , 
You can use
```
put localfilename remotepath
```
without the `/remotefilename` . That, however, won't cover the case when you want a different file name. We will cover that asap. Thanks for reporting.

**Comment by polmr** [comment]
Support for that use-case has been implemented in the new release 1.0.0
