### ISSUE TITLE
Sync with Synology NAS using Mega-CMD

### ISSUE THREAD

**Issue by stbx00** [meganz/MEGAcmd#723]
I'm using MegaCMD 1.4 on my Synology DSM 7.1. 
Synchronisation is working this using mega-cmd in putty: "sync /volume1/sauvegarde /MEGAsync" but it sometimes stopped and I have to log in with Putty and type "sync" to make it start again.

In the log file I only see : "[info: 12:56:11] Loaded sync: /volume1/sauvegarde to /MEGAsync"
Is there any way to make it sync without stopping ?
Thanks for your help...

**Comment by polmr** [comment]
You can increase verbosity with:
```
mega-log DEBUG
```
Note that in order for syncs to work, MEGAcmd server (mega-cmd-server) need to be running.

Also notice that `sync` command in current version provided in synology repositories may produce a crash: https://github.com/meganz/MEGAcmd/issues/703

We are working on procuring new installers soon enough that will have that very issue fixed

**Comment by polmr** [comment]
Newer releases of MEGAcmd for NAS (Synology/QNAP) featuring several improvements and fixes, can now be downloaded from here: https://mega.io/nas.
