### ISSUE TITLE
Downloading with free plan, and get "Reached bandwidth quota..." , will it keep trying?

### ISSUE THREAD

**Issue by ForceConstant** [meganz/MEGAcmd#729]
So I am trying to download a large file 6GB, and it gets partway, and then says reached quota.  My question is if I leave it, will mega-get resume once the quote renews for the day? 
Thanks.

**Comment by jx-mega** [comment]
Yes, it should.
Please also keep in mind that for free accounts, the transfer quota is measured per IP address, not per user account. 
If you have a dynamic IP address assigned by your ISP or you are using a VPN and received a "Transfer quota exceeded" warning without downloading anything from MEGA, that means others sharing the same IP may have used up the quota before you.
Once the free transfer quota is exceeded on your IP, you will have to wait to accrue more free quota and our servers automatically discard incomplete transfers after 48 hours of inactivity.

Alternatively, you can upgrade to a Pro account starting from 4.99 euros which provide extra storage and transfer quota as well as some exclusive advanced features: https://mega.nz/pro
If you got the Pro plan, your transfer will resume right away.

**Comment by ForceConstant** [comment]
Yes I verified that it does work. It will stay paused until more quota is a available and then keep downloading.
