### ISSUE TITLE
how to list only folders and respective export links

### ISSUE THREAD

**Issue by saiyyanwarrior** [meganz/MEGAcmd#73]
hello i am confused how to list only folders and respective export links i have read the userguide tried myself but i can't figure it out when i try i either get only folder names or the whole tree with export links
some help would be appreciated.

**Comment by polmr** [comment]
You can use the command `export` to list the exported files/folders within an specific path. e.g:
```
export /my/path/in/mega
```
Alternatively you can list a folder structure and show extended info (included folder links) with:
```
ls -aa /my/path/in/mega
```
Notice the double `a` is required to have more extra info (we will add a word on that in the info shown via `ls --help`)
