### ISSUE TITLE
mega-transfers empty output

### ISSUE THREAD

**Issue by kikadf** [meganz/MEGAcmd#731]
On linux armv7, with megacmd-1.5.1 the mega-transfers or from mega-cmd the transfers command give empty line.
If I use the --show-syncs, get same empty output. --summary show me only zeros.
$ mega-transfers --summary
NUM DOWNLOADS DOWNLOADED TOTAL % NUM UPLOADS UPLOADED TOTAL %
0 0.00 B 0.00 B 0.00% 0 0.00 B 0.00 B 0.00%

Can you confirm this issue, or is the problem in my own compiled version?

**Comment by polmr** [comment]
Are you sure you have ongoing transfers?

Bear in mind that `transfers` (no argument) and `transfers --summary` only refer to ongoing transfers.

Use `mega-transfers --show-completed` to list completed ones.

**Comment by kikadf** [comment]
Output is empty with --show-completed as well.

**Comment by polmr** [comment]
Yet, do transfers occur?

Note: `transfers` only reports transfers occurred since the server was running.

**Comment by kikadf** [comment]
Yes, it does. Syncing files up and down. Syncing works well, but I don't find output to check synced transfers. I'm searching on wrong place?

**Comment by polmr** [comment]
You are not :thinking: 
```
mega-transfers --show-syncs --show-completed
```
should list sync transfers, completed and onging.

I couldn't find a clear culprint where architecture could meddle with that. Specially with `mega-transfers --summary` being empty, but cannot tell for sure

Do logs report the transfers? (https://github.com/meganz/MEGAcmd/blob/master/contrib/docs/DEBUG.md)
```
mega-log DEBUG
```
~/.megaCmd/megacmdserver.log

**Comment by kikadf** [comment]
>mega-transfers --show-syncs --show-completed 
Works! Thank you for your help, it was my mistake.
