### ISSUE TITLE
WEBDAV not showing all files

### ISSUE THREAD

**Issue by tc0619** [meganz/MEGAcmd#735]
I am running megacmd in windows 10, I am able to start the webdav mapping, however when I map a drive for windows explorer it does not show all the folders and files.

I can see all the files when I go to the directory in megacmd with ls command, and I can see all of the files if I browse the webdav url in web browser.  it is only on the mapped drive that some files and folders do not appear.

any ideas for a solution, or anything else I can check?  I have dis-connected the mapped drive several times and the same files do not appear.

I have checked and the folder or files do not contain any special characters, or spaces at the end

**Comment by polmr** [comment]
Would you mind sharing a list of missing files files? or at least an example of one missing file in the listing.
