### ISSUE TITLE
backup -d <path> or backup -d <tag>

### ISSUE THREAD

**Issue by Xoquito** [meganz/MEGAcmd#74]
In Windows SO the instruction..

backup -d drive:\path\to\myfolder

..show an error and doesn't work.

Works fine as "backup -a" with:

backup -d <tag>

Example:

backup -d 62

**Comment by polmr** [comment]
@Xoquito , Are you using the latest version of MEGAcmd? 
```
$ version                                                                                   
MEGA CMD version: 0.9.9: code 90900
```
If not, please download it from https://mega.nz/cmd. 
If so, what is the exact error? What is the path shown if you list the backups with `backups` *. Is it the same as `drive:\path\to\myfolder`
* Notice that you can play with the option `--path-display-size=XX` if the path does not fit entirely.
