### ISSUE TITLE
manipulating duplicate files from the command file

### ISSUE THREAD

**Issue by thyresias** [meganz/MEGAcmd#741]
I discovered that Mega can have more than one file in the same folder with the same name (and, from what I saw looking for "duplicate", it can also have several folders with the same name).

I tried the following, starting with 2 files "empty.txt" (0 byte) and "hello.txt" (containing "hello")
```
> mega-cmd put empty.txt /test/file.txt
> mega-cmd put empty.txt /test/file.txt
> mega-cmd put hello.txt /test/file.txt
> mega-cmd put hello.txt /test/file.txt
```
I end up with 3 files with the same name: it seems that an empty file is stored only once, while a file containing something is always stored as a new file.
I can see the 3 files with `ls`.
If I issue `mega-cmd rm /test/file.txt`, the 3 files are deleted.
Is there a way to delete only 2 of them from the command line? (i.e. to identify each file in some way)

**Comment by polmr** [comment]
you can refer to a file by their handle. In order to see handles:
```
mega-ls -l --show-handles /test/ | grep file.txt
```
then mega-rm H:XXXXXX (with the handle you want removed)

**Comment by thyresias** [comment]
Thank you, it works perfectly.
Is there any reason why this is not documented in the user guide?
(e.g., experimental feature that may change without notice?)

**Comment by thyresias** [comment]
Found it: the user guide is completely out of sync with the features: mega-help -ff is the source for all features.
