### ISSUE TITLE
Download failed. error code:Already exists.

### ISSUE THREAD

**Issue by harunresitc** [meganz/MEGAcmd#76]
This is an error, but the file is not in my computer. Is this an error because an unsuccessful download has already occurred? How can I download file download history? I am using Raspbian Stretch, I am getting this error although I delete the hidden getxfer.xxxx.mega files in the folder where the files need to be moved.

**Comment by LorneWu** [comment]
I also encountered such problems these days because of SIGTERM( or ctrl-c ) during downloading.

> [err: 01:39:17] Download failed. error code: Already exists

I try to clean local cache `~/.megacmd` by `rm -rf ~/.megacmd/*`
And it works for me.
