### ISSUE TITLE
Filter and ignore files when using mega-sync

### ISSUE THREAD

**Issue by robert-zaremba** [meganz/MEGAcmd#766]
When using MEGAsync desktop app, in the UI we can set list of filename patterns to ignore.

I'm using Mega with Sway / wayland, and it has issue (the app starts but when I click on the tray app icon it doesn't who up). So I'm using `mega-cmd-server` + `mega-sync`.

I want to ignore some file patterns (eg temp files, cache etc...). How can I do it?

**Comment by polmr** [comment]
This should help:
```
mega-exclude --help
```

**Comment by robert-zaremba** [comment]
thanks, it works!
