### ISSUE TITLE
Extend website to download NAS binaries

### ISSUE THREAD

**Issue by BlackRose01** [meganz/MEGAcmd#776]
Please extend your website [https://mega.io/cmd#downloadapps](https://mega.io/cmd#downloadapps) that it is also possible to download the MEGAcmd binaries for NAS systems.

**Comment by polmr** [comment]
Newer releases of MEGAcmd for NAS (Synology/QNAP) featuring several improvements and fixes, can now be downloaded from here: https://mega.io/nas.
