### ISSUE TITLE
Video stream

### ISSUE THREAD

**Issue by hemiad** [meganz/MEGAcmd#78]
Hello
can api replay if a video is streamable or not ?
thank you
Best regards

**Comment by hemiad** [comment]
Hello
thank you for your repleay .
there a exemple : 
https://mega.nz/#!Sap0yADY!h7Vkv40IITYwec7gdSov_NP6bO29HOKMdzfcMhRt5T4  (Video not streamable)
https://mega.nz/#!OD5m3aaQ!qPGTYKvg-SMINGxKlvrl8iKAvyi4RLqZX5IlcbccLOk  (video streamable)

i want to know if there a solution with mega api to return this info.

**Comment by polmr** [comment]
I've imported both links and been able to reproduce them perfectly with MEGAcmd (serving using `webdav` command, as explained in the linked tutorial). Using vlc player. Same with MEGAsync. Only the web client seems currently unable to decode the video. There isn't a query to ask for such thing.

**Comment by polmr** [comment]
Webclient only support streaming mp4 and webm video. Others can be streamed via MEGAcmd/MEGASync. There isn't a query to ask for such thing. Issues here should be related to MEGAcmd
