### ISSUE TITLE
[1.6.x] Transfer progress lost after logout (even keeping session)

### ISSUE THREAD

**Issue by tonikelope** [meganz/MEGAcmd#788]
Hi. I have noticed that from version 1.6 onwards if you pause a transfer (I have tested it only with an upload), logout (even keeping the session) and then login the transfer starts from the beginning. In version 1.5.x it continued where it was going.

```
ArchLinux 6.1.19-1-lts
MEGAcmd version: 1.6.0.0: code 1060000
MEGA SDK version: 4.16.0
MEGA SDK Credits: https://github.com/meganz/sdk/blob/master/CREDITS.md
MEGA SDK License: https://github.com/meganz/sdk/blob/master/LICENSE
MEGAcmd License: https://github.com/meganz/megacmd/blob/master/LICENSE
MEGA Terms: https://mega.nz/terms
MEGA General Data Protection Regulation Disclosure: https://mega.nz/gdpr
Features enabled:
* CryptoPP
* SQLite
* inotify
* fdopendir
* FreeImage
* PCRE
* sync subsystem
```

Best regards.

**Comment by polmr** [comment]
We are working on a fix and will provide a new version with that fixed asap.
Thank you very much @tonikelope  for reporting that.
