### ISSUE TITLE
PUT command failing

### ISSUE THREAD

**Issue by cezar-pimentel** [meganz/MEGAcmd#791]
**Description**: I'm trying to start an upload (PUT) to my mega and I'm getting the message "The sever problably exited"

When running a put command (for an instance):
`MEGAclient.exe put -c -q <my-zip-file> /_MEGA_FOLDER/`

I get this response:
```
ERROR reading output (state change):
The sever problably exited.
ERROR reading output code:
```

**Actual Behavior**:
*The upload doesn't occur*

**Expected Behavior**:
*The upload should start and stick until it's finished* 

**Steps to Reproduce**:
1. Login to megaCmd
2. Run the put command
3. Wait for the error message a few seconds later

**MegaCMD Version**: 1.4.1.0: code 1040100 (64 bits)

**Comment by polmr** [comment]
Please, have your MEGAcmd version updated (https://mega.io/cmd) and try that again

**Comment by cezar-pimentel** [comment]
As a matter of fact I am using the latest version: 1.4.1.0: code 1040100 (64 bits)

**Comment by cezar-pimentel** [comment]
I've updated MEGAcmd to it's latest version **_1.6_** and it still giving the same error:

`ERROR reading output code: ERROR reading output (state change): The sever problably exited.109`

**Comment by cezar-pimentel** [comment]
I was wrong! I had two installations of megaCMD on my machine, and one of them wasn't updated properly.
I think that after updating the problem is gone.
Thanks for your time!

PS: I've created a pull request to correct a misspelled phrase.
