### ISSUE TITLE
Failed to upload: Access denied. Need explanation.

### ISSUE THREAD

**Issue by ZhmerenkaSolution** [meganz/MEGAcmd#801]
Hi, I'm using MEGAcmd (Windows) for a months and recently started to facing error `Failed to upload: Access denied` on command `put -c <localfolder> <megafolder>` which MEGAcmd throwing after hours of beginning the process. I supposed that cause of this problem is Windows folder permissions, so I ran MEGAcmd with administrator rights, but this have no effect, and also I have all administrator rights on whole uploading folder. 
Anyway, If the problem really in Windows file/folder permissions, can I somehow (in log or console output) see path of file/folder in which MEGAcmd fails to upload?

**Comment by polmr** [comment]
Hi @ZhmerenkaSolution 
you can list all completed transfers (including failed) with `transfers --show-completed --limit=99999`

Also the log would indicate which one has failed too. In order to obtain the log, you can run MEGAcmd Server in verbose mode:

Please, open your task manager and ensure there is no MEGAcmdServer.exe process running, and then run in Powershell console:

```
PS C:\Users\YOURUSER\AppData\Local\MEGAcmd> $env:LOCALAPPDATA\MEGAcmd\MEGAcmdServer.exe --debug-full > megacmd.log
```

**Comment by ZhmerenkaSolution** [comment]
@polmr Ok, I did it, and now I see in log some weird folder which I don't see in windows explorer nor as a hidden element:
`[API:err: 20:35:12] Can't open local directory<localfolder>\╨Т╤Ц╨┤╨┤╤Ц╨╗ ╨╜╨╡╤Ц╨╜╤В╤А╤Г╨╖╨╕╨▓╨╜╨╕╤Е ╨╝╨╡╤В╨╛╨┤╤Ц╨▓ ╨╝╨╕╤В╨╜╨╛╨│╨╛ ╨║╨╛╨╜╤В╤А╨╛╨╗╤О\12000 msa
[API:debug: 20:35:12] MegaRecursiveOperation finished with error [-11] - bytes: 0 of 0
[API:warn: 20:35:12] Transfer (UPLOAD) finished with error: Access denied File: Line
[API:debug: 20:35:12] MegaFolderUploadController dtor is being called from main thread
[API:err: 20:35:12] Failed to upload: Access denied`
I suppose that I should somehow clean MEGAcmd cache?

**Comment by polmr** [comment]
That's unexpected. Would you mind sharing that log with us? 

Since it may contain sensitive information, you can send it to support@mega.nz and refer to this issue in the title.

**Comment by ZhmerenkaSolution** [comment]
@polmr I sent log file, waiting for reply and further instructions.

**Comment by polmr** [comment]
Thanks @ZhmerenkaSolution 
Just to be clear, MEGAcmd got updated lately and after that you started experiencing these issues, right?
We will investigate scenarios where cyrilic paths are involved.

**Comment by ZhmerenkaSolution** [comment]
@polmr Yes, it started about 3-4 weeks ago.

**Comment by polmr** [comment]
Thanks again for all your inputs @ZhmerenkaSolution and apologies for the inconveniences.

We have detected a few issues with non ASCII characters in the installation folder PATH, that prevent among other thing, resumption and reusing configuration from previous executions.

As a temporary workaround you may want to try to move your MEGAcmd installation folder into a path that does not include your user name (e.g: C:/MEGAcmd), then launch manually MEGAcmdServer.exe before launching MEGAcmdShell.exe.

Regarding the upload issue, it seems there may be some actual problem accessing a file causing the operation to end:
```
[API:err: 20:35:12] Can't open local directory F:\Line\XXXXXXXXXXX\12000 msa
[API:debug: 20:35:12] MegaRecursiveOperation finished with error [-11] - bytes: 0 of 0
[API:warn: 20:35:12] Transfer (UPLOAD) finished with error: Access denied File: Line
```
with XXXXXXX being some lengthy non ASCII folder name.

**Comment by ZhmerenkaSolution** [comment]
@polmr I found what cause the issue - `12000 msa` is not a file, but a folder on which for some reason I didn't have Windows access (that's why I didn't saw it first time when error appear and which also might point that is not relate to MEGAcmd update). MEGAcmd itself seems work fine with non ASCII path/files (because I have almost all folders/files in non ASCII), just screw up logging/output. And I don't see any issue with non ASCII installation folder path of MEGAcmd itself (but still moved to C:\MEGAcmd just in case).
So you might want:
1) Fix non ASCII folder/file logging/output.
2) Fix that error mechanism when MEGAcmd for some reason don't have access to a single folder it completely stops uploading which make you totally unable (until you make something with this folder) to update all another folders and files in cloud. I suppose in most cases users will want simply log/output error with this folder/file, skip it and continue uploading.
Thanks for supporting anyway.
