### ISSUE TITLE
[Solved] Sync Stopped [Synology DSM7]

### ISSUE THREAD

**Issue by romsweb** [meganz/MEGAcmd#804]
Hey Guys,

Sync stopped sinced 14 days for an ignored reason

I tried to reboot my NAS without success (work by the past).

When I lunch it I have
.==============================================================================.
|                __  __ _____ ____    _                      _                 |
|               |  \/  | ___|/ ___|  / \   ___ _ __ ___   __| |                |
|               | |\/| | \  / |  _  / _ \ / __| '_ ` _ \ / _` |                |
|               | |  | | /__\ |_| |/ ___ \ (__| | | | | | (_| |                |
|               |_|  |_|____|\____/_/   \_\___|_| |_| |_|\__,_|                |
|                                                                              |
|                                    SERVER                                    |
`==============================================================================´
[info: 06:00:52] Loaded sync: /volume1/Cloud/Mega to /_Formations
Segmentation fault (core dumped)

I uninstalled it, reinstalled it without success too.

Can you guys help me?

synorom@DS920:~$ ps aux | grep -i megacmd
synorom   3491  0.0  0.0  23244  2384 pts/0    S+   17:05   0:00 grep --color=auto -i megacmd

I also tried:

synorom@DS920:~$ mega-reload
[Initiating server in background. Log: /var/services/homes/synorom/.megaCmd/megacmdserver.log]
                            Resuming session ...                             
Reloading account...
Fetching nodes ||########################################||(3/3 MB: 100.00 %) 
[Server is probably down. Type to respawn or reconnect to it]
Error reading size of partial output: 111

Thank you

**Comment by polmr** [comment]
Newer releases of MEGAcmd for NAS (Synology/QNAP) featuring several improvements and fixes, can now be downloaded from here: https://mega.io/nas.

**Comment by romsweb** [comment]
Hello,

thank you

looks like it’s the same 1.4 version as I already have.

**Comment by polmr** [comment]
You are correct @romsweb , we will amend it as soon as possible.
Apologies for the inconveniences

**Comment by polmr** [comment]
@romsweb Please, open the URL in an incognito window: you shall see the new links there.

**Comment by romsweb** [comment]
@polmr You made my day!!

Thank you!
