### ISSUE TITLE
megacmd on ubuntu ppc64el IBM Power 8

### ISSUE THREAD

**Issue by Pat90** [meganz/MEGAcmd#81]
Hello!
I wan't to install megacmd package on my server ubuntu 16.04 installed on IBM Power8 PPC64EL.
The package megacmd-xUbuntu_16.04_amd64.deb doesn't work (is it compliled for intel proc?).
Can someone give me the package compiled for ppc64el platform or explain me how to obtain it?

Thank You.

**Comment by polmr** [comment]
Building instructions: https://github.com/meganz/MEGAcmd#building-megacmd
