### ISSUE TITLE
login with meganz user to remote encrypted folder

### ISSUE THREAD

**Issue by yulidb** [meganz/MEGAcmd#810]
Hi,
I want to use mega-login to access an encrypted meganz folder, while logged in to my account. is there a way to do this? 
I was able to login to the remote folder using mega-login <folder_url> <password>, or to my account using mega-login <username> <password>, but once I was logged in I wasn't able to access the remote folder.

Thanks!

**Comment by polmr** [comment]
No, MEGAcmd cannot be logged into both an account an an exported folder at the same time.

You can however logout keeping session, speeding the subsequent session resumption:
```
$ mega-session                                                                                                                       
Your (secret) session is:  XXXXXXXXXXX
$ mega-logout --keep-session
$ mega-login <folder_url>
.... play with your folder ...
$ mega-logout 
$ mega-login XXXXXXXXXXX
```

**Comment by yulidb** [comment]
but I won't be able to download files using my premium user from the remote folder?

**Comment by polmr** [comment]
No, you won't.

Notice that you can always download (mega-get) / import (mega-import) files from a folder link while logged in your account using:
```
mega-get https://mega.nz/folder/XXXXXX#YYYYYYYYYYYY/file/ZZZZZZZZ
```
You can get that url opening your folder link with your browser and right click on it -> Get Link

**Comment by yulidb** [comment]
thanks!
