### ISSUE TITLE
Syntax Error When Attempting to Stream a Folder Using Mega CMD WebDav

### ISSUE THREAD

**Issue by Kittyxox** [meganz/MEGAcmd#811]
Hello, 

I have been using Mega CMD and have successfully logged in. However, I am facing an issue when trying to stream a folder using WebDav. By default, it runs on localhost and port 4443. 

I would like to use my VPS IP address and custom port but I am unsure of the correct syntax. I have tried using "webdav 'sample' --public --port 4848" but it did not work. I have also opened port 4848 but the issue persists.

Can you please advise on the correct syntax to use when streaming a folder using Mega CMD WebDav with a custom IP address and port?

**Comment by polmr** [comment]
> correct syntax 
```
webdav -d --all
webdav 'sample' --public --port=4848
```
(notice the `=` instead of the space)


Note that changing public-ness or port will require to stop serving all locations in order for changes to take effect (hence the `webdav -d --all`)

**Comment by polmr** [comment]
Note that the IP is the IP of the computer running MEGAcmd. MEGAcmd lists (via `webdav` without parameters) listed locations using loopback IP, but if you've made it `--public` you should be able to access it from your LAN using its local IP, of from the outside, using your ISP provided public IP (but you'd need to make sure port 4848 _natted_ accordingly, and no firewall is preventing accessing such port)

**Comment by Kittyxox** [comment]
> Note that the IP is the IP of the computer running MEGAcmd. MEGAcmd lists (via `webdav` without parameters) listed locations using loopback IP, but if you've made it `--public` you should be able to access it from your LAN using its local IP, of from the outside, using your ISP provided public IP (but you'd need to make sure port 4848 _natted_ accordingly, and no firewall is preventing accessing such port)

Ok  that works, thanks. 
Could you tell me how to add username and password in the webdav server?

**Comment by polmr** [comment]
[No username/password support](https://github.com/meganz/MEGAcmd/blob/master/contrib/docs/WEBDAV.md#:~:text=At%20the%20moment%20of%20writing%20this%20tutorial%2C%20there%20is%20no%20authentication%20mechanisms%2C%20hence%20you%20don%27t%20need%20to%20worry%20about%20providing%20a%20user%20name/password)
