### ISSUE TITLE
megaclient and megacmdshell - LS wildcards does not work recursively

### ISSUE THREAD

**Issue by phhowe17** [meganz/MEGAcmd#821]
I'm trying to find files of a certain name in a directory structure.

\folderA\
   \folderB\
        file.abc
        file.xyz

If I cd \folderA\folderB\ and issue this command it lists file.xyz

 ls -lr *.xyz

If instead I cd \folderA (one directory above) and issue the same command I get the error

"[API:err: 01:31:12] Couldn't find "*.xyz"

I'm running MEGAcmd version: 1.6.1.4: code 1060104 (64 bits) on Windows 11.

**Comment by polmr** [comment]
wildcard expansion does work with subfolders.

You could use `*/*.xyz` to select files/folders with that suffix within the all first level childs

Or use 
```
find --pattern="*.xyz"
```
To use searching, instead of wildcard expansions

**Comment by phhowe17** [comment]
*/*.xyz does not work.  It only works if you know the entire wildcard path to the target.  you need to know the folder depth.  It also doesn't actually use -r as  */*/*.xyz matches even without the option.  But does not find files other than at that specific path depth.

Not being from a linux background I expected wild cards to match on files as in Windows.  Googling shows that "find" is the preferred command in linux.  Even though linux uses "-name" instead of "--pattern"

Looks like the "find" command I would need is

    find --pattern="*.xyz" --type=f

to match only on files.
