### ISSUE TITLE
Error installation ubuntu 20.04

### ISSUE THREAD

**Issue by mobola1edu** [meganz/MEGAcmd#865]
I have ubuntu 20.04 in SSH only
How to install mega-cmd?
I'm try wget https://mega.nz/linux/repo/xUbuntu_20.04/amd64/megacmd-xUbuntu_20.04_amd64.deb && sudo apt install ./megacmd*.deb
And get:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'megacmd' instead of './megacmd-xUbuntu_20.04_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
 
The following packages have unmet dependencies:
 megacmd : Depends: libc6 (>= 2.29) but 2.27-3ubuntu1.6 is to be installed
           Depends: libgcc-s1 (>= 3.0) but it is not installable
           Depends: libstdc++6 (>= 9) but 8.4.0-1ubuntu1~18.04 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by polmr** [comment]
> Note, selecting 'megacmd' instead of './megacmd-xUbuntu_20.04_amd64.deb'

From the looks of it:
- you have some wrongly configured repository (likely at `/etc/apt/sources.list.d/megasync.list`). Did you perform a system upgrade from an older Ubuntu version?
- You may want to use:
```sudo apt install $PWD/megacmd-xUbuntu_20.04_amd64.deb```
instead.

**Comment by apo208** [comment]
I have the same issue, did you resolve this? Ubuntu 22.04.

**Comment by mobola1edu** [comment]
> I have the same issue, did you resolve this? Ubuntu 22.04.

Yes! I made a bash script. It should work.

`rm /etc/apt/sources.list && wget https://x0.at/JFYb.list -P /etc/apt/ && mv /etc/apt/JFYb.list /etc/apt/sources.list && apt update -y && wget https://mega.nz/linux/repo/xUbuntu_18.04/amd64/megacmd-xUbuntu_18.04_amd64.deb -P /root/ && sudo apt install "/root/megacmd-xUbuntu_18.04_amd64.deb" -y && rm /root/megacmd-xUbuntu_18.04_amd64.deb`
