### ISSUE TITLE
Error megacmd google colab

### ISSUE THREAD

**Issue by essjrbhz** [meganz/MEGAcmd#871]
Hello,

I have been using Google Colab Pro to transfer 12tb from google drive to mega. From a week to now I can no longer log into megacmd. It gives the following message:

[mega-cmd-server is probably down. Type to respawn or reconnect to it].

Using another mega account, it works normally.

Can anyone help me?

**Comment by reinvolfi** [comment]
I've got the exactly same problem, can anyone help?
