### ISSUE TITLE
Add a script for installing the dependencies

### ISSUE THREAD

**Issue by SubhrajyotiSen** [meganz/MEGAcmd#9]
The `configure`script checks for configuration and shows errors and then the user has to manually install dependencies and keep repeating the process multiple times.

It would be much more convenient if there was a script to install all required dependencies at one go

**Comment by polmr** [comment]
You can find in the README a list of packages required by MEGAcmd (for Ubuntu 16.04):
```
For convenience here is a list of packages for ubuntu 16.04: autoconf libtool g++ libcrypto++-dev libz-dev sqlite3-dev libsqlite3-dev libssl-dev libcurl4-openssl-dev libreadline-dev libpcre++-dev libsodium-dev
```
Correspondence in other systems should be straight forward.
