### ISSUE TITLE
Question: how to hide email in mega-cmd shell after logging in

### ISSUE THREAD

**Issue by gituser23234235234887** [meganz/MEGAcmd#951]
# How do I hide my email?  
### I do not want any identifying information in the shell  
file names and stuff is fine but I really do not want my email to be always visible.  
### How do I customize what the shell prompt is like anyway?  
hopefully I do not have to change it in the source code and compile my own package.

**Comment by polmr** [comment]
I am afraid MEGAcmd does not support customizing prompt. We will get notice of that and consider adding the possibility.

Notice, that you can use MEGAcmd in non interactive mode, from a shell of your liking, where you don't see MEGAcmd Shell prompt.
