### ISSUE TITLE
Megacmd Linux Failed to confirm security upgrade: Temporarily not available

### ISSUE THREAD

**Issue by MFYDev** [meganz/MEGAcmd#983]
### MEGAcmd version

1.7.0

### Operating System/Platform

Linux

### Platform version. In the case of Linux, please enter the Linux distribution you are using.

Ubuntu 22.04

### Steps

1. log in to the mega cmd
2. see the error message
3. [Initiating MEGAcmd server in background. Log: /root/.megaCmd/megacmdserver.log]
 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|                                                                                                             Your account's security needs upgrading.                                                                                                             |
|                                                                                                              Please execute: "confirm --security".                                                                                                               |
|                                                                                                This only needs to be done once. If you have seen this message for                                                                                                |
|                                                                                                            this account before, please exit MEGAcmd.                                                                                                             |
 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

:/$ confirm --security
[err: 16:10:43] Failed to confirm security upgrade: Temporarily not available

### Expected behavior

no errors

### Actual behavior

[Initiating MEGAcmd server in background. Log: /root/.megaCmd/megacmdserver.log]
 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|                                                                                                             Your account's security needs upgrading.                                                                                                             |
|                                                                                                              Please execute: "confirm --security".                                                                                                               |
|                                                                                                This only needs to be done once. If you have seen this message for                                                                                                |
|                                                                                                            this account before, please exit MEGAcmd.                                                                                                             |
 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

:/$ confirm --security
[err: 16:10:43] Failed to confirm security upgrade: Temporarily not available

**Comment by polmr** [comment]
Would the issue persist if you try again or login with your account in a browser (https://mega.io) ?

**Comment by MFYDev** [comment]
Hi @polmr I already tried for multiple times and I also installed megacmd on every system, this issue only happens on Linux, directly log in through browser has no errors, but I have to use megacmd, I need to mount the webdav to my server to use it

**Comment by MFYDev** [comment]
[API:err: 14:57:59] Unable to FileAccess::fopen('/root/.megaCmd/apiFolder_0/jid'): sysstat() failed: error code: 2: No such file or directory
[API:err: 14:57:59] Unable to FileAccess::fopen('/root/.megaCmd/apiFolder_1/jid'): sysstat() failed: error code: 2: No such file or directory
[API:err: 14:57:59] Unable to FileAccess::fopen('/root/.megaCmd/apiFolder_2/jid'): sysstat() failed: error code: 2: No such file or directory
[API:err: 14:57:59] Unable to FileAccess::fopen('/root/.megaCmd/apiFolder_3/jid'): sysstat() failed: error code: 2: No such file or directory
[API:err: 14:57:59] Unable to FileAccess::fopen('/root/.megaCmd/apiFolder_4/jid'): sysstat() failed: error code: 2: No such file or directory

.==============================================================================================================================================================================================================================================================================================================================================================================.
|                                                                                                                                                                __  __ _____ ____    _                      _                                                                                                                                                                 |
|                                                                                                                                                               |  \/  | ___|/ ___|  / \   ___ _ __ ___   __| |                                                                                                                                                                |
|                                                                                                                                                               | |\/| | \  / |  _  / _ \ / __| '_ ` _ \ / _` |                                                                                                                                                                |
|                                                                                                                                                               | |  | | /__\ |_| |/ ___ \ (__| | | | | | (_| |                                                                                                                                                                |
|                                                                                                                                                               |_|  |_|____|\____/_/   \_\___|_| |_| |_|\__,_|                                                                                                                                                                |
|                                                                                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                    SERVER                                                                                                                                                                                    |
`==============================================================================================================================================================================================================================================================================================================================================================================´
[info: 14:57:59] Listening to petitions ... 
[info: 14:57:59] Resuming session...
[info: 14:58:00] Fetching nodes ... 
[API:err: 14:58:00] Failed AES-GCM decryption: HashVerificationFilter: message hash or MAC not valid
[API:err: 14:58:00] Failed to GCM decrypt ^!keys.
[API:err: 14:58:00] Failed AES-GCM decryption: HashVerificationFilter: message hash or MAC not valid
[API:err: 14:58:00] Cannot extract TLV records for ATTR_DEVICE_NAMES
[API:err: 14:58:00] Failed AES-GCM decryption: HashVerificationFilter: message hash or MAC not valid
[API:err: 14:58:00] Failed to GCM decrypt ^!keys.
[API:err: 14:58:00] Error processing new received values for the Key Manager (ug command)
[API:err: 14:58:00] Failed AES-GCM decryption: HashVerificationFilter: message hash or MAC not valid
[API:err: 14:58:00] syncConfigIOContext: JSON config data is malformed
[API:err: 14:58:00] Failed AES-GCM decryption: HashVerificationFilter: message hash or MAC not valid
[API:err: 14:58:00] syncConfigIOContext: JSON config data is malformed
[API:err: 14:58:00] Couldn't load internal sync configs from disk: -3

this is hugely affected my workflow and I will seriously need a fix for this, thank you so much

**Comment by SJai-mega** [comment]
Hello. Please email support@mega.nz from your MEGA registered account
Mention that you are from Github user ID: [MFYDev] and the Github issue:https://github.com/meganz/MEGAcmd/issues/983  so that we can assist further. Please let us know when you have emailed us so that we can escalate the issue. Thanks! ^SJ

**Comment by SJai-mega** [comment]
Hello. We have received your email. We will reply back to your email as soon as our team has checked your account. Thanks!  ^SJ
