### ISSUE TITLE
Questions on syncing between DiskStation and Mega

### ISSUE THREAD

**Issue by rally2me** [meganz/MEGAcmd#986]
### MEGAcmd version

1.7.0

### Operating System/Platform

Windows

### Platform version. In the case of Linux, please enter the Linux distribution you are using.

Windows 10

### Steps

1. sync /path/to/local/folder /folder/in/mega
2. quit --only-shell

### Expected behavior

That a sync would be established with no further action required.

### Actual behavior

A sync was established, but I'm not sure if that's all required.

----------------------
This is not an issue as such, but I've was redirected to this page after asking some questions to Mega support over email. I've read the usage instructions but I'm not confident I've fully understood them. I have a set of folders on NAS which I want to keep in sync on Mega.

- Am I correct to say that, if I've ssh'd into my Diskstation from Windows and have established a sync using [sync /path/to/local/folder /folder/in/mega], I should just use [quit --only-shell] to keep the server running? There is nothing else required from me to keep the sync running? It will run until I use [quit]?
- If my Diskstation restarts, does mega-cmd (and my sync tasks) resume on start-up? If not, is there a way to make this happen? This [guide](https://www.reddit.com/r/synology/comments/wfh0ki/how_to_back_up_your_synology_nas_to_meganz/) from 2022 suggests I need to set up a triggered task - is that still the case?
- How do I view sync tasks I have set-up (including those that are not currently uploading/downloading)? Using [transfers] options seem to let me view currently syncing/past sync events, but I don't understand how to get a summary of all sync tasks I've set-up.

**Comment by polmr** [comment]
> Am I correct to say that, if I've ssh'd into my Diskstation from Windows and have established a sync using [sync /path/to/local/folder /folder/in/mega], I should just use [quit --only-shell] to keep the server running? There is nothing else required from me to keep the sync running? It will run until I use [quit]?

It will run as long as MEGAcmd Server process (`mega-cmd-server`) is running. If you quit your ssh session, that will not be the case. You can alternatively, for instance, initiate `mega-cmd-server` with `nohup`:
```
nohup mega-cmd-server &
```
and you can even close your ssh session and MEGAcmd Server should be kept running.
> If my Diskstation restarts, does mega-cmd (and my sync tasks) resume on start-up? If not, is there a way to make this happen? This [guide](https://www.reddit.com/r/synology/comments/wfh0ki/how_to_back_up_your_synology_nas_to_meganz/) from 2022 suggests I need to set up a triggered task - is that still the case?
Yes, this is still the case. The proposed solution seem a valid one.
> How do I view sync tasks I have set-up (including those that are not currently uploading/downloading)? Using [transfers] options seem to let me view currently syncing/past sync events, but I don't understand how to get a summary of all sync tasks I've set-up.
Typing `sync`  (with no arguments) in your MEGAcmd Shell (`mega-cmd`), would give you a summary and status of configured syncs.

**Comment by rally2me** [comment]
Thanks polmr. I don't understand what `quit --only-shell` does then. From the user guide:

"In order to enable synchronisation and backup features, and for efficiency running commands, MEGAcmd runs a server process in the background which the MEGAcmd shell or the script commands forward requests to. The server keeps running in the background until it is told to close with the quit command. If you want it to keep running when you quit the interactive shell (to keep sync and backup runnign for example), use `quit --only-shell`."

It also looks like I don't understand the difference between the shell and the server. I've been using Windows command prompt to ssh into my Diskstation, then using `mega-cmd` to run commands, including experimenting with sync tasks. Entering `mega-cmd-server` after ssh (rather than `mega-cmd`) gives me the message 'Another instance of MEGAcmd Server is running'. Should I first use `nohup mega-cmd-server &` to keep the server running after quitting, and then use `mega-cmd` to set up my sync tasks?

How would I stop the server running after using `nohup mega-cmd-server &`? I couldn't see any mention of nohup in the usage guide.

**Comment by rally2me** [comment]
Hi @polmr,

I appreciate the further explanation, I think I'm getting there. Would you mind reviewing this for me:

**Trying to achieve:**

A sync task to be set up between DiskStation and Mega Cloud and run until I tell it to stop

**Steps I took:**

- Opened Windows Command Prompt
- ssh'd into my DiskStation
- Typed `cmd-server`
- Logged into Mega
- Set up a sync task using `sync`
- Typed `nohup mega-cmd-server &`
- Closed Windows Command Prompt

**Comment by polmr** [comment]
`cmd-server` ?

Steps that should work:

- Open Windows Command Prompt
- ssh'd into my DiskStation
- ensure there's no `mega-cmd-server` running
```
pgrep mega-cmd-server > /dev/null || echo all good
```
- launch MEGAcmd in background, _dettaching_ it from current bash/ssh shell:
```
nohup mega-cmd-server &
```
- Open a MEGAcmd shell to login into your account
```
mega-cmd
MEGA CMD>  login ....
```
- Set up a sync using sync
- quit MEGAcmd Shell
```
quit --only-shell
```
- Ensure MEGAcmd Server is still running
```
pgrep mega-cmd-server > /dev/null && echo all good
```
- Closed Windows Command Prompt (closing ssh session)

**Comment by rally2me** [comment]
Great, will run through those and see what I get, thanks. Yes - `cmd-server` was a typo.

**Comment by rally2me** [comment]
I fell at the first hurdle:

```
name@DiskStation555:~$ pgrep mega-cmd-server > /dev/null || echo all good
-sh: pgrep: command not found
all good
name@DiskStation555:~$ 
```

I went through a whole conversation with chatgpt to try and get pgrep installed/working, with no luck.

**Comment by polmr** [comment]
That step is just to find if there's such process, you can do that manually with whatever tool there is available to look for processes. eg:
```
ps aux | grep mega-cmd-server
```
... or even skip it, it's just a check :-)

**Comment by rally2me** [comment]
Excellent, thanks for your help.
