### ISSUE TITLE
Error Fetching Nodes in MEGA CMD on Synology NAS - Server Down Issue

### ISSUE THREAD

**Issue by Mattia0880** [meganz/MEGAcmd#989]
### MEGAcmd version

1.4.1

### Operating System/Platform

Synology

### Platform version. In the case of Linux, please enter the Linux distribution you are using.

Synology DSM 7.2.1-69057 Update 5

### Steps

	1.	I started the terminal on my Synology NAS.
	2.	I entered the command mega-login (email).
	3.	I entered my password.
	4.	I entered the authentication code generated by my app (code).
	5.	I waited for the nodes to load.

### Expected behavior

I expected the login procedure to complete successfully and my MEGA nodes to load without errors.

### Actual behavior

MEGA CMD Version: 1.4.0-1000

After entering the authentication code, I received the following error message:

[API:info: 19:48:13] Fetching nodes ...
Error reading size of partial output: 0##########################||(154/154 MB: 100.00 %)
[Server is probably down. Type to respawn or reconnect to it]

It seems the server might be down, but I’m not sure how to proceed. I tried reconnecting, but the issue persists.
![Screenshot 2024-07-25 at 00 11 54](https://github.com/user-attachments/assets/f88a6e21-3541-40cf-b737-cc8038e80427)

**Comment by dhanton** [comment]
Hi, this might be a bug with an older version. Could you try using version 1.7.0? [[Download links for Synology]](https://mega.nz/folder/ogBQnbKa#CoRlU5uarTf4XpY3TbPELQ/folder/R9pADabJ).

**Comment by Mattia0880** [comment]
Hello, the bug has been fixed by updating the plugin to the latest version
