### ISSUE TITLE
mega-mv --use-pcre not working

### ISSUE THREAD

**Issue by jpercyasnet** [meganz/MEGAcmd#990]
### MEGAcmd version

1.7.0

### Operating System/Platform

Linux

### Platform version. In the case of Linux, please enter the Linux distribution you are using.

Linux Mint 21.3

### Steps

Trying to use wild card via pcre but get the error.
mega-mv --use-pcre 199101*.mpg 199101Philippines

[err: 18:27:25] 199101*.mpg: No such file or directory

### Expected behavior

move files with wild card expression

### Actual behavior

[err: 18:27:25] 199101*.mpg: No such file or directory

**Comment by dhanton** [comment]
Hi, I believe pcre is not needed for this. Could you try wrapping the path in quotes? I.e.:
```
mega-mv "199101*.mpg" 199101Philippines
```

**Comment by jpercyasnet** [comment]
The quotes worked! Thank you
