### ISSUE TITLE
Cannot log in, stuck at fetching nodes

### ISSUE THREAD

**Issue by MFYDev** [meganz/MEGAcmd#991]
### MEGAcmd version

1.7.0

### Operating System/Platform

MacOS

### Platform version. In the case of Linux, please enter the Linux distribution you are using.

Macos Latest

### Steps

log in

### Expected behavior

should be able to log in

### Actual behavior

<img width="558" alt="image" src="https://github.com/user-attachments/assets/3ad562eb-5953-4f08-ae8a-e59f6c0806d4">

I am stuck here

**Comment by tt-mega** [comment]
Hello,
Does the issue also happen if you access your account via Browser or other apps?
If yes, please contact us at support@mega.co.nz as the issue could be related to your Mega account and not to the MegaCMD.
Thanks!
