### ISSUE TITLE
ignore sync for .* except someone

### ISSUE THREAD

**Issue by FilMar** [meganz/MEGAcmd#996]
Hi, i have a question, how can i ignore from sync all .* files and dir except someone?
With megaSync this is possible with .megaignore file that have -:dir  for exclude and +:dir for include but from what i see it's not used by megacmd, there is a way to do?
Thanks for help.

**Comment by dhanton** [comment]
Hi, `.megaignore` files are not yet supported in MEGAcmd, but they're being actively worked on. They will be included in a future release. Until then you could try using the `exclude` command (although it doesn't support inclusion rules).

Closing this as planned.
