### ISSUE TITLE
mega-get redownloads already existing files

### ISSUE THREAD

**Issue by carfesh** [meganz/MEGAcmd#997]
### MEGAcmd version

1.7.0

### Operating System/Platform

Windows

### Platform version. In the case of Linux, please enter the Linux distribution you are using.

Windows 11 Pro

### Steps

Download a folder from mega to the local computer. Run the download again later to sync changes.

### Expected behavior

Existing files should be skipped.

### Actual behavior

Files are downloaded again, with a (1) placed before the file extension.

**Comment by dhanton** [comment]
Hi! This is the expected behavior of `mega-get`. To automatically apply cloud changes to your local files (without re-downloading if there are no changes), use the `sync` command.

**Comment by dhanton** [comment]
Not directly, AFAIK. 

If the link you're downloading from is an exported folder, you could try logging-in directly to it. To do so, log out first, and then do `mega-login https://mega.nz/folder/...`. You should now have read-only access to the folder, allowing you to run most commands like `ls`, `cat`, etc.; and (if I remember correctly), also `sync`.
